import { useEffect, useState } from 'react';
import { useOutletContext } from 'react-router-dom';
import type { ModelOutletContext } from './ModelView.js';
import { useSelection } from '../selection.js';

interface Finding {
  id: string;
  severity: 'critical' | 'warning' | 'info';
  category: 'structural' | 'logical' | 'consistency' | 'coverage';
  sourceRef?: string;
  explanation: string;
  impact?: string;
  reachCount?: number;
  autoGenerated: boolean;
}

const SEV_STYLE: Record<string, string> = {
  critical: 'bg-red-900/60 text-red-300 border-red-800',
  warning: 'bg-amber-900/60 text-amber-300 border-amber-800',
  info: 'bg-blue-900/50 text-blue-300 border-blue-800',
};

export function FindingsView() {
  const { modelId } = useOutletContext<ModelOutletContext>();
  const { select } = useSelection();
  const [findings, setFindings] = useState<Finding[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [filter, setFilter] = useState<string>('all');

  useEffect(() => {
    let cancelled = false;
    setLoading(true);
    fetch(`/findings/${modelId}`)
      .then((r) => (r.ok ? r.json() : r.json().then((e) => Promise.reject(new Error(e.error || 'Failed')))))
      .then((d) => { if (!cancelled) setFindings(d.findings ?? []); })
      .catch((e) => { if (!cancelled) setError(e.message); })
      .finally(() => { if (!cancelled) setLoading(false); });
    return () => { cancelled = true; };
  }, [modelId]);

  if (loading) return <p className="text-slate-400">Analyzing model…</p>;
  if (error) return <p className="text-red-400">{error}</p>;

  const counts = findings.reduce<Record<string, number>>((acc, f) => {
    acc[f.severity] = (acc[f.severity] ?? 0) + 1;
    return acc;
  }, {});
  const shown = filter === 'all' ? findings : findings.filter((f) => f.severity === filter);

  return (
    <div className="space-y-4">
      <div className="flex items-center gap-2">
        {(['all', 'critical', 'warning', 'info'] as const).map((s) => (
          <button
            key={s}
            onClick={() => setFilter(s)}
            className={`px-3 py-1 text-xs rounded-md capitalize transition-colors ${
              filter === s ? 'bg-slate-700 text-white' : 'bg-slate-900 text-slate-400 hover:text-slate-200'
            }`}
          >
            {s}{s !== 'all' && counts[s] ? ` (${counts[s]})` : ''}
          </button>
        ))}
        <span className="ml-auto text-xs text-slate-600">{findings.length} finding{findings.length === 1 ? '' : 's'}</span>
      </div>

      {shown.length === 0 ? (
        <p className="text-sm text-slate-500">
          {filter === 'all' ? 'No findings — model looks clean.' : `No ${filter} findings.`}
        </p>
      ) : (
        <div className="space-y-2">
          {shown.map((f) => (
            <button
              key={f.id}
              onClick={() => f.sourceRef && select({ modelId, cellId: f.sourceRef, label: f.sourceRef, value: undefined })}
              className={`w-full text-left rounded-lg border px-4 py-3 transition-colors hover:bg-slate-900/60 ${SEV_STYLE[f.severity]}`}
            >
              <div className="flex items-center gap-2 mb-1">
                <span className="text-[10px] font-semibold uppercase">{f.severity}</span>
                <span className="text-[10px] text-slate-500 uppercase">{f.category}</span>
                {f.sourceRef && <span className="text-[10px] font-mono text-slate-500">{f.sourceRef}</span>}
                {f.impact && <span className="ml-auto text-[10px] text-slate-400">{f.impact}</span>}
              </div>
              <p className="text-sm text-slate-200">{f.explanation}</p>
            </button>
          ))}
        </div>
      )}
    </div>
  );
}
