import { useEffect, useState } from 'react';
import { useOutletContext } from 'react-router-dom';
import type { ModelOutletContext } from './ModelView.js';
import { useSelection } from '../selection.js';
import { formatExcelValue } from '../format.js';

interface ImpactEstimate {
  outputId: string;
  outputName: string;
  observedValue: unknown;
  expectedValue: unknown;
  delta: number | null;
  percentDelta: number | null;
}

interface Finding {
  id: string;
  severity: 'critical' | 'warning' | 'info';
  category: 'structural' | 'logical' | 'consistency' | 'coverage';
  sourceRef?: string;
  explanation: string;
  impact?: string;
  reachCount?: number;
  autoGenerated: boolean;
  expectedFormula?: string;
  observedFormula?: string;
  likelyCause?: string;
  impactChain?: string[];
  impactEstimates?: ImpactEstimate[];
}

const SEV_STYLE: Record<string, { chip: string; border: string }> = {
  critical: { chip: 'bg-red-900/60 text-red-300', border: 'border-red-800/60' },
  warning: { chip: 'bg-amber-900/60 text-amber-300', border: 'border-amber-800/60' },
  info: { chip: 'bg-blue-900/50 text-blue-300', border: 'border-blue-800/50' },
};

export function FindingsView() {
  const { modelId } = useOutletContext<ModelOutletContext>();
  const { select } = useSelection();
  const [findings, setFindings] = useState<Finding[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [filter, setFilter] = useState<string>('all');

  useEffect(() => {
    let cancelled = false;
    setLoading(true);
    fetch(`/findings/${modelId}`)
      .then((r) => (r.ok ? r.json() : r.json().then((e) => Promise.reject(new Error(e.error || 'Failed')))))
      .then((d) => { if (!cancelled) setFindings(d.findings ?? []); })
      .catch((e) => { if (!cancelled) setError(e.message); })
      .finally(() => { if (!cancelled) setLoading(false); });
    return () => { cancelled = true; };
  }, [modelId]);

  if (loading) return <p className="text-slate-400">Analyzing model…</p>;
  if (error) return <p className="text-red-400">{error}</p>;

  const counts = findings.reduce<Record<string, number>>((acc, f) => {
    acc[f.severity] = (acc[f.severity] ?? 0) + 1;
    return acc;
  }, {});
  const shown = filter === 'all' ? findings : findings.filter((f) => f.severity === filter);

  return (
    <div className="space-y-4">
      <div className="flex items-center gap-2">
        {(['all', 'critical', 'warning', 'info'] as const).map((s) => (
          <button
            key={s}
            onClick={() => setFilter(s)}
            className={`px-3 py-1 text-xs rounded-md capitalize transition-colors ${
              filter === s ? 'bg-slate-700 text-white' : 'bg-slate-900 text-slate-400 hover:text-slate-200'
            }`}
          >
            {s}{s !== 'all' && counts[s] ? ` (${counts[s]})` : ''}
          </button>
        ))}
        <span className="ml-auto text-xs text-slate-600">{findings.length} finding{findings.length === 1 ? '' : 's'}</span>
      </div>

      {shown.length === 0 ? (
        <p className="text-sm text-slate-500">
          {filter === 'all' ? 'No findings — model looks clean.' : `No ${filter} findings.`}
        </p>
      ) : (
        <div className="space-y-3">
          {shown.map((f) => (
            <FindingCard key={f.id} finding={f} onInspect={() => f.sourceRef && select({ modelId, cellId: f.sourceRef, label: f.sourceRef, value: undefined })} />
          ))}
        </div>
      )}
    </div>
  );
}

function FindingCard({ finding: f, onInspect }: { finding: Finding; onInspect: () => void }) {
  const style = SEV_STYLE[f.severity];
  const rich = f.expectedFormula || f.likelyCause || f.impactChain?.length || f.impactEstimates?.length;

  return (
    <div className={`rounded-lg border bg-slate-900/50 overflow-hidden ${style.border}`}>
      <button onClick={onInspect} className="w-full text-left px-4 py-3 hover:bg-slate-900/60 transition-colors">
        <div className="flex items-center gap-2 mb-1">
          <span className={`text-[10px] font-semibold uppercase px-1.5 py-0.5 rounded ${style.chip}`}>{f.severity}</span>
          <span className="text-[10px] text-slate-500 uppercase">{f.category}</span>
          {f.sourceRef && <span className="text-[10px] font-mono text-slate-500">{f.sourceRef}</span>}
          {f.impact && <span className="ml-auto text-[10px] text-slate-400">{f.impact}</span>}
        </div>
        <p className="text-sm text-slate-200">{f.explanation}</p>
      </button>

      {rich && (
        <div className="px-4 pb-4 pt-1 border-t border-slate-800/60 space-y-3">
          {(f.expectedFormula || f.observedFormula) && (
            <div className="grid grid-cols-2 gap-3">
              <div>
                <p className="text-[10px] uppercase text-slate-500 mb-1">Observed</p>
                <p className="font-mono text-xs text-red-300 bg-slate-950 rounded px-2 py-1.5 break-all">{f.observedFormula}</p>
              </div>
              <div>
                <p className="text-[10px] uppercase text-slate-500 mb-1">Expected</p>
                <p className="font-mono text-xs text-emerald-300 bg-slate-950 rounded px-2 py-1.5 break-all">{f.expectedFormula}</p>
              </div>
            </div>
          )}

          {f.likelyCause && (
            <div>
              <p className="text-[10px] uppercase text-slate-500 mb-1">Likely cause</p>
              <p className="text-xs text-slate-300">{f.likelyCause}</p>
            </div>
          )}

          {f.impactChain && f.impactChain.length > 0 && (
            <div>
              <p className="text-[10px] uppercase text-slate-500 mb-1">Downstream impact</p>
              <p className="text-xs font-mono text-slate-400">{f.impactChain.join(' → ')}</p>
            </div>
          )}

          {f.impactEstimates && f.impactEstimates.length > 0 && (
            <div>
              <p className="text-[10px] uppercase text-slate-500 mb-1">Estimated impact (if corrected)</p>
              <div className="rounded-md border border-slate-800 divide-y divide-slate-800/60 overflow-hidden">
                {f.impactEstimates.slice(0, 6).map((e) => (
                  <div key={e.outputId} className="flex items-center gap-3 px-3 py-1.5 text-xs">
                    <span className="flex-1 text-slate-300 truncate">{e.outputName}</span>
                    <span className="font-mono text-slate-500">{formatExcelValue(e.observedValue)}</span>
                    <span className="text-slate-600">→</span>
                    <span className="font-mono text-slate-100">{formatExcelValue(e.expectedValue)}</span>
                    <span className={`font-mono w-20 text-right ${e.percentDelta == null ? 'text-slate-600' : e.percentDelta > 0 ? 'text-emerald-400' : e.percentDelta < 0 ? 'text-red-400' : 'text-slate-500'}`}>
                      {e.percentDelta == null ? '—' : `${e.percentDelta > 0 ? '+' : ''}${e.percentDelta.toFixed(1)}%`}
                    </span>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
