import { useCallback, useEffect, useState } from 'react';
import { useOutletContext } from 'react-router-dom';
import type { ModelOutletContext } from './ModelView.js';

interface TestDef {
  id: string;
  name: string;
  category: string;
  description?: string;
  autoGenerated: boolean;
}

interface TestResult {
  testId: string;
  name: string;
  category: string;
  status: 'pass' | 'fail' | 'error' | 'skip';
  actual?: unknown;
  expected?: unknown;
  message?: string;
  executedAt: string;
}

const STATUS_STYLE: Record<string, string> = {
  pass: 'bg-emerald-900/60 text-emerald-300',
  fail: 'bg-red-900/60 text-red-300',
  error: 'bg-amber-900/60 text-amber-300',
  skip: 'bg-slate-800 text-slate-400',
};

export function TestsView() {
  const { modelId } = useOutletContext<ModelOutletContext>();
  const [tests, setTests] = useState<TestDef[]>([]);
  const [results, setResults] = useState<Map<string, TestResult> | null>(null);
  const [allPass, setAllPass] = useState<boolean | null>(null);
  const [running, setRunning] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const load = useCallback(async () => {
    const res = await fetch(`/tests/${modelId}`);
    const data = await res.json();
    setTests(data.tests ?? []);
  }, [modelId]);

  useEffect(() => { load(); }, [load]);

  const generate = async () => {
    setGenerating(true);
    setError(null);
    try {
      const res = await fetch(`/tests/${modelId}/generate`, { method: 'POST' });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || 'Generation failed');
      await load();
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Generation failed');
    } finally {
      setGenerating(false);
    }
  };

  const run = async () => {
    setRunning(true);
    setError(null);
    try {
      const res = await fetch(`/tests/${modelId}/run?evidence=true`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: '{}',
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || 'Test run failed');
      setAllPass(data.allPass);
      setResults(new Map((data.results as TestResult[]).map((r) => [r.testId, r])));
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Test run failed');
    } finally {
      setRunning(false);
    }
  };

  const remove = async (testId: string) => {
    await fetch(`/tests/${modelId}/${testId}`, { method: 'DELETE' });
    setResults(null);
    setAllPass(null);
    await load();
  };

  return (
    <div className="space-y-4">
      <div className="flex items-center gap-3">
        <button
          onClick={generate}
          disabled={generating}
          className="px-3 py-1.5 rounded-md text-sm bg-slate-800 text-slate-200 hover:bg-slate-700 disabled:opacity-40 transition-colors"
        >
          {generating ? 'Generating…' : 'Generate Structural Tests'}
        </button>
        <button
          onClick={run}
          disabled={running || tests.length === 0}
          className="px-3 py-1.5 rounded-md text-sm bg-emerald-600 text-white hover:bg-emerald-500 disabled:opacity-40 disabled:cursor-not-allowed transition-colors"
        >
          {running ? 'Running…' : `Run All (${tests.length})`}
        </button>
        {allPass != null && (
          <span className={`text-xs font-medium px-2 py-1 rounded ${allPass ? 'bg-emerald-900/60 text-emerald-300' : 'bg-red-900/60 text-red-300'}`}>
            {allPass ? 'ALL PASS' : 'FAILURES'}
          </span>
        )}
        {error && <span className="text-xs text-red-400">{error}</span>}
      </div>

      {tests.length === 0 ? (
        <p className="text-sm text-slate-600">
          No tests yet. Generate structural tests to check for broken references, circular dependencies, and formula inconsistencies.
        </p>
      ) : (
        <div className="rounded-lg border border-slate-800 divide-y divide-slate-800/60 overflow-hidden">
          {tests.map((t) => {
            const r = results?.get(t.id);
            return (
              <div key={t.id} className="px-4 py-2.5 flex items-center gap-3 text-sm">
                {r ? (
                  <span className={`text-[10px] font-semibold uppercase px-1.5 py-0.5 rounded ${STATUS_STYLE[r.status]}`}>
                    {r.status}
                  </span>
                ) : (
                  <span className="text-[10px] font-semibold uppercase px-1.5 py-0.5 rounded bg-slate-800 text-slate-500">
                    not run
                  </span>
                )}
                <span className="flex-1 text-slate-200 truncate" title={t.description}>{t.name}</span>
                <span className="text-xs text-slate-600">{t.category}</span>
                {t.autoGenerated && <span className="text-[10px] text-slate-600 uppercase">auto</span>}
                {r?.message && <span className="text-xs text-red-400/80 truncate max-w-64" title={r.message}>{r.message}</span>}
                <button
                  onClick={() => remove(t.id)}
                  className="text-xs text-slate-600 hover:text-red-400 transition-colors"
                >
                  Delete
                </button>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
