import { Hono } from 'hono';
import crypto from 'crypto';
import { ModelRuntime, runModelTests } from '@xlent/core';
import type { ModelTestDefinition, EvidenceRecord, ScenarioOverride } from '@xlent/core';
import { store, snapshotStore, testStore, evidenceStore } from '../../store.js';
import { logExecution } from '../../monitoring.js';
import { rateLimitMiddleware } from '../../middleware/rateLimit.js';
import { idempotencyMiddleware } from '../../middleware/idempotency.js';

export const v1Router = new Hono();

v1Router.use('*', rateLimitMiddleware);
v1Router.use('*', idempotencyMiddleware);

/** POST /v1/models/:slug/execute — Run latest published version */
v1Router.post('/models/:slug/execute', async (c) => {
  const slug = c.req.param('slug');
  const model = store.getBySlug(slug);
  if (!model) return c.json({ error: 'Model not found' }, 404);
  if (model.status !== 'published') return c.json({ error: 'Model not published' }, 403);

  const workbook = store.getWorkbook(model.id);
  if (!workbook) return c.json({ error: 'Workbook not found' }, 500);

  const body = await c.req.json().catch(() => ({}));
  const overrides: ScenarioOverride[] | undefined = Array.isArray(body.overrides) ? body.overrides : undefined;

  const runtime = new ModelRuntime(model, workbook);
  const started = performance.now();
  const results = runtime.run(overrides);
  const durationMs = performance.now() - started;

  // E11.3 — log every execution for monitoring/anomaly detection
  logExecution({
    modelId: model.id,
    modelVersion: model.version,
    durationMs,
    inputs: { overrides: overrides ?? [] },
    outputs: results,
    success: true,
  });

  // Optional evidence
  const withEvidence = c.req.query('evidence') === 'true';
  let evidenceId: string | undefined;
  if (withEvidence) {
    const tests = testStore.listTests(model.id);
    const defs: ModelTestDefinition[] = tests.map((t: any) => ({ id: t.id, modelId: t.modelId, name: t.name, category: t.category, assertion: t.assertion, autoGenerated: t.autoGenerated }));
    const testResults = defs.length > 0 ? runModelTests(model, workbook, defs, overrides) : [];
    const allPass = testResults.every((r) => r.status === 'pass' || r.status === 'skip');
    const dataHash = crypto.createHash('sha256').update(JSON.stringify({ results, testResults })).digest('hex');

    const record: EvidenceRecord = {
      id: crypto.randomUUID(),
      modelId: model.id,
      modelVersion: model.version,
      executedAt: new Date().toISOString(),
      inputs: Object.fromEntries((model.parameters || []).map((p) => [p.id, p.currentValue])),
      overrides: overrides ?? [],
      outputs: results,
      tests: testResults,
      allTestsPass: allPass,
      checksum: dataHash,
      reproducible: true,
      purpose: 'scenario_run',
    };
    evidenceStore.store(record);
    evidenceId = record.id;
  }

  return c.json({ slug, semver: model.semver, results, evidenceId });
});

/** POST /v1/models/:slug/versions/:semver/execute — Run pinned version */
v1Router.post('/models/:slug/versions/:semver/execute', async (c) => {
  const { slug, semver } = c.req.param();
  const model = store.getBySlug(slug);
  if (!model) return c.json({ error: 'Model not found' }, 404);

  const snapshot = snapshotStore.getByVersion(model.id, semver);
  if (!snapshot) return c.json({ error: `Version ${semver} not found` }, 404);

  const pinnedModel = snapshot.data;
  const workbook = store.getWorkbook(model.id);
  if (!workbook) return c.json({ error: 'Workbook not found' }, 500);

  const body = await c.req.json().catch(() => ({}));
  const overrides: ScenarioOverride[] | undefined = Array.isArray(body.overrides) ? body.overrides : undefined;

  const runtime = new ModelRuntime(pinnedModel, workbook);
  const started = performance.now();
  const results = runtime.run(overrides);
  const durationMs = performance.now() - started;

  logExecution({
    modelId: model.id,
    modelVersion: pinnedModel.version,
    durationMs,
    inputs: { overrides: overrides ?? [] },
    outputs: results,
    success: true,
  });

  return c.json({ slug, semver, results });
});
