import type {
  Model, AssuranceLevel, AssuranceGateResult,
  ModelTestResult, DebugFinding, EvidenceRecord, ModelTestDefinition,
} from './types.js';
import { reconcileContract } from './contractReconcile.js';

export const ASSURANCE_ORDER: AssuranceLevel[] = ['UNASSESSED', 'TESTED', 'VERIFIED', 'VALIDATED'];

export function assuranceRank(level: AssuranceLevel): number {
  return ASSURANCE_ORDER.indexOf(level);
}

export function nextLevel(level: AssuranceLevel): AssuranceLevel | null {
  const i = ASSURANCE_ORDER.indexOf(level);
  return i < ASSURANCE_ORDER.length - 1 ? ASSURANCE_ORDER[i + 1] : null;
}

export interface AssuranceContext {
  model: Model;
  tests: ModelTestDefinition[];
  testResults: ModelTestResult[] | null; // null = never run
  findings: DebugFinding[];
  evidence: EvidenceRecord[];
  /** steward approval is a human act — passed in as a flag */
  stewardApproved: boolean;
}

/**
 * E9.2 — Evaluate whether a model can advance to a target assurance level.
 * Advance-only, never skip: you can only move to the immediate next level.
 */
export function checkAssuranceGate(ctx: AssuranceContext, targetLevel: AssuranceLevel): AssuranceGateResult {
  const current = ctx.model.assuranceLevel ?? 'UNASSESSED';

  // Never advance backward and never skip a level
  if (assuranceRank(targetLevel) <= assuranceRank(current)) {
    return { canAdvance: false, blockers: [`Model is already ${current} — cannot move to ${targetLevel}`] };
  }
  if (assuranceRank(targetLevel) !== assuranceRank(current) + 1) {
    return {
      canAdvance: false,
      blockers: [`Cannot skip levels: ${current} → ${targetLevel}. Must advance to ${nextLevel(current)} first.`],
    };
  }

  const blockers: string[] = [];

  switch (targetLevel) {
    case 'TESTED': {
      // all auto-generated structural tests pass + at least 1 user-defined test exists
      const auto = ctx.tests.filter((t) => t.autoGenerated);
      const userDefined = ctx.tests.filter((t) => !t.autoGenerated);
      if (userDefined.length === 0) blockers.push('Add at least one user-defined test (structural, mathematical, or business)');
      if (auto.length === 0) blockers.push('Generate structural tests first');
      if (ctx.testResults) {
        const failing = ctx.testResults.filter((r) => r.status === 'fail' || r.status === 'error');
        if (failing.length > 0) blockers.push(`${failing.length} test(s) failing: ${failing.map((f) => f.name).join(', ')}`);
      } else if (auto.length > 0) {
        blockers.push('Run the test suite to confirm auto-generated structural tests pass');
      }
      break;
    }

    case 'VERIFIED': {
      // all tests pass + no critical findings + evidence record exists
      if (!ctx.testResults || ctx.testResults.length === 0) {
        blockers.push('Run the test suite');
      } else {
        const failing = ctx.testResults.filter((r) => r.status === 'fail' || r.status === 'error');
        if (failing.length > 0) blockers.push(`${failing.length} test(s) failing`);
      }
      const critical = ctx.findings.filter((f) => f.severity === 'critical');
      if (critical.length > 0) blockers.push(`${critical.length} critical finding(s) must be resolved (see Debug)`);
      if (ctx.evidence.length === 0) blockers.push('No evidence record — run the model with evidence capture to establish reproducibility');
      break;
    }

    case 'VALIDATED': {
      // contract exists + contract reconciliation clean + steward approval
      if (!ctx.model.contract) {
        blockers.push('Define a model contract (intent must be explicit — Rule 11)');
      } else {
        const intentConflicts = reconcileContract(ctx.model, ctx.model.contract);
        const openConflicts = intentConflicts.filter((f) => f.severity === 'critical');
        if (openConflicts.length > 0) {
          blockers.push(`${openConflicts.length} unresolved contract conflict(s) (see Debug → intent)`);
        }
      }
      if (!ctx.stewardApproved) blockers.push('Steward approval required to reach VALIDATED');
      break;
    }

    default:
      break;
  }

  return { canAdvance: blockers.length === 0, blockers };
}
