import type { Model, ModelTestDefinition } from './types.js';
import { detectCycles } from './graph.js';
import crypto from 'crypto';

// Generates structural tests automatically from model analysis
export function generateStructuralTests(model: Model): ModelTestDefinition[] {
  const tests: ModelTestDefinition[] = [];

  // Test: no circular dependencies
  const cycles = detectCycles(model.graph);
  tests.push({
    id: crypto.randomUUID(),
    modelId: model.id,
    name: 'No circular dependencies',
    category: 'structural',
    assertion: { type: 'equals', left: '__meta_cycle_count', right: 0 },
    description: cycles.length > 0
      ? `Found ${cycles.length} cycle(s): ${cycles.map(c => c.join(' → ')).join('; ')}`
      : undefined,
    autoGenerated: true,
  });

  // Test: no external references
  if (model.discovery.externalReferences > 0) {
    tests.push({
      id: crypto.randomUUID(),
      modelId: model.id,
      name: 'No external workbook references',
      category: 'structural',
      assertion: { type: 'equals', left: '__meta_external_refs', right: 0 },
      description: `${model.discovery.externalReferences} external reference(s) detected`,
      autoGenerated: true,
    });
  }

  // Test: no unsupported functions
  if (model.discovery.unsupportedFunctions > 0) {
    tests.push({
      id: crypto.randomUUID(),
      modelId: model.id,
      name: 'No unsupported functions',
      category: 'structural',
      assertion: { type: 'equals', left: '__meta_unsupported_fns', right: 0 },
      description: `${model.discovery.unsupportedFunctions} unsupported function(s) detected`,
      autoGenerated: true,
    });
  }

  // Test: all outputs produce finite numeric values (non-error)
  for (const output of model.outputs) {
    if (output.confidence === 'HIGH') {
      tests.push({
        id: crypto.randomUUID(),
        modelId: model.id,
        name: `Output "${output.name}" is numeric`,
        category: 'structural',
        assertion: { type: 'is_numeric', left: output.id },
        description: `Verify output ${output.name} computes to a finite number`,
        autoGenerated: true,
      });
    }
  }

  return tests;
}

// Evaluates meta-assertions that reference model metadata rather than execution results
export function resolveMetaValue(ref: string, model: Model): unknown {
  switch (ref) {
    case '__meta_cycle_count':
      return detectCycles(model.graph).length;
    case '__meta_external_refs':
      return model.discovery.externalReferences;
    case '__meta_unsupported_fns':
      return model.discovery.unsupportedFunctions;
    default:
      return undefined;
  }
}
