import crypto from 'crypto';
import type { Model, ModelContract, DebugFinding } from './types.js';

function fid(...parts: unknown[]): string {
  return crypto.createHash('sha1').update(parts.map(String).join('|')).digest('hex').slice(0, 12);
}

/**
 * E8.2 — Reconcile declared contract intent against discovered model structure.
 * Conflicts surface as `intent` findings. Contract is the highest authority.
 */
export function reconcileContract(model: Model, contract: ModelContract): DebugFinding[] {
  const findings: DebugFinding[] = [];
  const norm = (s: string) => s.toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim();

  const discoveredInputs = new Map(model.parameters.map((p) => [norm(p.name), p]));
  const discoveredOutputs = new Map(model.outputs.map((o) => [norm(o.name), o]));

  // Extra contract input (declared but not found in model) → critical
  for (const di of contract.declaredInputs) {
    if (!discoveredInputs.has(norm(di.name))) {
      findings.push({
        id: fid('intent-input-missing', di.name),
        severity: 'critical',
        category: 'intent',
        explanation: `Contract declares input "${di.name}" but the model has no matching parameter`,
        autoGenerated: false,
      });
    }
  }

  // Missing contract input (discovered but not declared) → warning
  for (const p of model.parameters) {
    if (!contract.declaredInputs.some((di) => norm(di.name) === norm(p.name))) {
      findings.push({
        id: fid('intent-input-undeclared', p.name),
        severity: 'warning',
        category: 'intent',
        sourceRef: `${p.sourceCell.sheet}!${p.sourceCell.ref}`,
        explanation: `Input "${p.name}" is used by the model but not declared in the contract`,
        autoGenerated: false,
      });
    }
  }

  // Extra contract output (declared but not found) → critical
  for (const dO of contract.declaredOutputs) {
    if (!discoveredOutputs.has(norm(dO.name))) {
      findings.push({
        id: fid('intent-output-missing', dO.name),
        severity: 'critical',
        category: 'intent',
        explanation: `Contract declares output "${dO.name}" but the model produces no matching output`,
        autoGenerated: false,
      });
    }
  }

  // Output mismatch: declared output exists but its expectation conflicts → critical
  for (const dO of contract.declaredOutputs) {
    const discovered = discoveredOutputs.get(norm(dO.name));
    if (!discovered) continue;
    if (dO.expectation === 'non-negative' && typeof discovered.value === 'number' && discovered.value < 0) {
      findings.push({
        id: fid('intent-output-negative', dO.name),
        severity: 'critical',
        category: 'intent',
        sourceRef: `${discovered.sourceCell.sheet}!${discovered.sourceCell.ref}`,
        explanation: `Contract expects output "${dO.name}" to be non-negative, but it evaluates to ${discovered.value}`,
        autoGenerated: false,
      });
    }
  }

  // Invariant not testable (references a name the model doesn't have) → warning
  const knownNames = new Set([...discoveredInputs.keys(), ...discoveredOutputs.keys()]);
  for (const inv of contract.invariants) {
    const names = inv.expression.match(/[A-Za-z][A-Za-z0-9 ]*/g) ?? [];
    const testable = names.some((n) => knownNames.has(norm(n)));
    if (!testable) {
      findings.push({
        id: fid('intent-invariant-untestable', inv.id),
        severity: 'warning',
        category: 'intent',
        explanation: `Invariant ${inv.id} ("${inv.expression}") cannot be evaluated — no matching model input or output`,
        autoGenerated: false,
      });
    }
  }

  const order = { critical: 0, warning: 1, info: 2 } as const;
  findings.sort((a, b) => order[a.severity] - order[b.severity]);
  return findings;
}
