import crypto from 'crypto';
import type { Model, DebugFinding, DependencyGraph } from './types.js';
import type { ParsedWorkbook } from './parser.js';
import { detectCycles } from './graph.js';
import { detectPatternBreaks } from './pattern.js';
import { quantifyFormulaImpact, impactChain } from './quantify.js';
import { resolveLabels } from './understand.js';

function fid(...parts: unknown[]): string {
  return crypto.createHash('sha1').update(parts.map(String).join('|')).digest('hex').slice(0, 12);
}

/** Analyze a model and produce classified findings (E7.1). */
export function analyzeFindings(model: Model, workbook: ParsedWorkbook | undefined): DebugFinding[] {
  const findings: DebugFinding[] = [];
  const graph: DependencyGraph = model.graph;

  // structural: circular dependencies
  const cycles = detectCycles(graph);
  for (const cycle of cycles) {
    findings.push({
      id: fid('cycle', cycle.join(',')),
      severity: 'critical',
      category: 'structural',
      sourceRef: cycle[0],
      explanation: `Circular dependency: ${cycle.join(' → ')} → ${cycle[0]}`,
      autoGenerated: true,
      regressionTest: {
        name: 'No circular dependencies',
        category: 'structural',
        assertion: { type: 'equals', left: '__meta_cycle_count', right: 0 },
        description: 'Model must not contain circular dependency cycles',
      },
    });
  }

  // structural: external references (from discovery)
  if (model.discovery?.externalReferences > 0) {
    findings.push({
      id: fid('extrefs', model.discovery.externalReferences),
      severity: 'warning',
      category: 'structural',
      explanation: `${model.discovery.externalReferences} external reference(s) to other workbooks — these cannot be resolved deterministically`,
      autoGenerated: true,
    });
  }

  // Build reach map once (downstream output count per cell)
  const terminalSet = new Set(findTerminals(graph));
  const outEdges = new Map<string, string[]>();
  for (const e of graph.edges) {
    if (!outEdges.has(e.from)) outEdges.set(e.from, []);
    outEdges.get(e.from)!.push(e.to);
  }
  const reachCache = new Map<string, Set<string>>();
  const reachableOutputs = (start: string): Set<string> => {
    if (reachCache.has(start)) return reachCache.get(start)!;
    const seen = new Set<string>();
    const queue = [start];
    while (queue.length) {
      const cur = queue.shift()!;
      for (const next of outEdges.get(cur) ?? []) {
        if (seen.has(next)) continue;
        seen.add(next);
        queue.push(next);
      }
    }
    const outputs = new Set([...seen].filter((n) => terminalSet.has(n)));
    reachCache.set(start, outputs);
    return outputs;
  };

  // logical: dead inputs (parameters that reach no output)
  // Group by label so a labeled series (Revenue B2:F2) yields ONE finding, not N.
  // Guard: skip entirely for data-table workbooks (reference datasets) where the
  // input:output ratio is extreme — dead-end inputs are the intended shape there,
  // not a defect. (Damodaran-style industry datasets: hundreds of inputs, 1 output.)
  const inputCount = model.parameters.length;
  const outputCount = Math.max(1, model.outputs.length);
  const isDataTable = inputCount / outputCount >= 50;
  if (workbook && !isDataTable) {
    const deadByLabel = new Map<string, string[]>();
    for (const p of model.parameters) {
      const cellId = `${p.sourceCell.sheet}!${p.sourceCell.ref}`;
      if (reachableOutputs(cellId).size === 0) {
        if (!deadByLabel.has(p.name)) deadByLabel.set(p.name, []);
        deadByLabel.get(p.name)!.push(cellId);
      }
    }
    for (const [name, cellIds] of deadByLabel) {
      findings.push({
        id: fid('dead-input', name),
        severity: 'info',
        category: 'logical',
        sourceRef: cellIds[0],
        explanation: cellIds.length > 1
          ? `Input "${name}" (${cellIds.length} cells) does not affect any output — potential dead input`
          : `Input "${name}" does not affect any output — potential dead input`,
        reachCount: 0,
        autoGenerated: true,
      });
    }
  } else if (workbook && isDataTable) {
    findings.push({
      id: fid('data-table-shape'),
      severity: 'info',
      category: 'logical',
      explanation: `Reference-dataset shape detected (${inputCount} inputs, ${outputCount} output${outputCount === 1 ? '' : 's'}) — dead-input analysis suppressed; this looks like a lookup/reference table, not a computational model`,
      autoGenerated: true,
    });
  }

  // consistency: same label resolved to different cells with differing formats
  if (workbook) {
    const byLabel = new Map<string, { cellId: string; format?: string }[]>();
    for (const o of model.outputs) {
      const cellId = `${o.sourceCell.sheet}!${o.sourceCell.ref}`;
      const key = o.name;
      if (!byLabel.has(key)) byLabel.set(key, []);
      byLabel.get(key)!.push({ cellId, format: o.format });
    }
    for (const [label, cells] of byLabel) {
      if (cells.length < 2) continue;
      const formats = new Set(cells.map((c) => c.format ?? 'General'));
      if (formats.size > 1) {
        findings.push({
          id: fid('fmt', label),
          severity: 'warning',
          category: 'consistency',
          sourceRef: cells[0].cellId,
          explanation: `Output "${label}" appears ${cells.length}× with inconsistent formats (${[...formats].join(', ')})`,
          autoGenerated: true,
        });
      }
    }
  }

  // structural: pattern-consistency defects (E7.4) — the constitution's primary case
  if (workbook) {
    const labels = resolveLabels(workbook, graph);
    const labelOf = (cellId: string) => labels.get(cellId) ?? cellId;
    for (const f of detectPatternBreaks(workbook)) {
      // downstream chain for the narrative (Revenue → EBITDA → FCF → IRR)
      if (f.sourceRef) f.impactChain = impactChain(graph, f.sourceRef, labelOf);
      // quantified impact: re-run with the expected formula and diff outputs
      if (f.sourceRef && f.expectedFormula) {
        try {
          const est = quantifyFormulaImpact(model, workbook, f.sourceRef, f.expectedFormula);
          if (est.length) f.impactEstimates = est;
        } catch { /* corrected formula not evaluable — leave unquantified */ }
      }
      findings.push(f);
    }
  }

  // --- Remaining §14 structural classes ---

  if (workbook) {
    const labels = resolveLabels(workbook, graph);
    const labelOf = (cellId: string) => labels.get(cellId) ?? cellId;

    // unexpected hardcodes: a literal number inside a run of formula cells
    findings.push(...detectHardcodes(workbook, labelOf));

    // missing formulas: a numeric gap inside a formula band
    findings.push(...detectMissingFormulas(workbook, labelOf));

    // disconnected outputs: a formula cell that reaches nothing and isn't an output
    findings.push(...detectDisconnected(model, labelOf));

    // broken references: a formula referencing a cell with no content
    findings.push(...detectBrokenRefs(workbook, labelOf));
  }

  // coverage: outputs with no test coverage are surfaced at the API layer (needs test store)

  // Order: critical → warning → info
  const order = { critical: 0, warning: 1, info: 2 };
  findings.sort((a, b) => order[a.severity] - order[b.severity]);
  return findings;
}

/** A literal number embedded in a horizontal/vertical run of formula cells. */
function detectHardcodes(workbook: ParsedWorkbook, labelOf: (id: string) => string): DebugFinding[] {
  const out: DebugFinding[] = [];
  for (const sheet of workbook.sheets) {
    const byRow = new Map<number, { formula: boolean; cellId: string; type: string }[]>();
    for (const c of sheet.cells) {
      const row = parseInt(c.address.ref.replace(/[A-Z]/g, ''), 10);
      if (!byRow.has(row)) byRow.set(row, []);
      byRow.get(row)!.push({ formula: !!c.formula, cellId: `${sheet.name}!${c.address.ref}`, type: c.type });
    }
    for (const cells of byRow.values()) {
      const formulaCount = cells.filter((c) => c.formula).length;
      if (formulaCount < 3) continue; // need a real series
      for (const c of cells) {
        if (!c.formula && c.type === 'number') {
          out.push({
            id: fid('hardcode', c.cellId),
            severity: 'warning',
            category: 'structural',
            sourceRef: c.cellId,
            explanation: `"${labelOf(c.cellId)}" is a hard-coded number inside a row of ${formulaCount} formulas — value won't recalculate when inputs change`,
            observedFormula: '(literal value)',
            autoGenerated: true,
            regressionTest: {
              name: `"${labelOf(c.cellId)}" remains formula-driven`,
              category: 'structural',
              assertion: { type: 'is_numeric', left: c.cellId },
              description: `Regression guard: ${c.cellId} should be a computed cell, not a hardcoded literal`,
            },
          });
        }
      }
    }
  }
  return out;
}

/** A numeric/blank gap in the middle of a formula band (missing formula). */
function detectMissingFormulas(workbook: ParsedWorkbook, labelOf: (id: string) => string): DebugFinding[] {
  const out: DebugFinding[] = [];
  for (const sheet of workbook.sheets) {
    const cellMap = new Map<string, { formula?: string; type: string }>();
    for (const c of sheet.cells) cellMap.set(c.address.ref, { formula: c.formula, type: c.type });

    // Group formula cells by column, look for a blank/number gap between formulas
    const byCol = new Map<string, number[]>();
    for (const c of sheet.cells) {
      if (!c.formula) continue;
      const col = c.address.ref.replace(/[0-9]/g, '');
      const row = parseInt(c.address.ref.replace(/[A-Z]/g, ''), 10);
      if (!byCol.has(col)) byCol.set(col, []);
      byCol.get(col)!.push(row);
    }
    for (const [col, rows] of byCol) {
      if (rows.length < 3) continue;
      const sorted = [...rows].sort((a, b) => a - b);
      for (let i = 0; i < sorted.length - 1; i++) {
        const a = sorted[i];
        const b = sorted[i + 1];
        if (b - a === 2) {
          const gapRef = `${col}${a + 1}`;
          const gap = cellMap.get(gapRef);
          const cellId = `${sheet.name}!${gapRef}`;
          if (gap && !gap.formula) {
            out.push({
              id: fid('missing', cellId),
              severity: 'warning',
              category: 'structural',
              sourceRef: cellId,
              explanation: `"${labelOf(cellId)}" has no formula but sits between formulas in ${col}${a} and ${col}${b} — possible missing calculation`,
              observedFormula: gap.type === 'blank' ? '(empty)' : '(literal value)',
              expectedFormula: `(formula matching ${col}${a} / ${col}${b})`,
              likelyCause: 'Missing or deleted formula in a series',
              autoGenerated: true,
              regressionTest: {
                name: `"${labelOf(cellId)}" is computed`,
                category: 'structural',
                assertion: { type: 'is_numeric', left: cellId },
                description: `Regression guard: ${cellId} must evaluate to a finite number`,
              },
            });
          }
        }
      }
    }
  }
  return out;
}

/** A formula cell that depends on inputs but reaches no terminal output. */
function detectDisconnected(model: Model, labelOf: (id: string) => string): DebugFinding[] {
  const out: DebugFinding[] = [];
  const terminal = new Set(findTerminals(model.graph));
  const outEdges = new Map<string, string[]>();
  for (const e of model.graph.edges) {
    if (!outEdges.has(e.from)) outEdges.set(e.from, []);
    outEdges.get(e.from)!.push(e.to);
  }
  const inEdges = new Map<string, number>();
  for (const e of model.graph.edges) inEdges.set(e.to, (inEdges.get(e.to) ?? 0) + 1);

  for (const node of model.graph.nodes) {
    const hasFormula = (inEdges.get(node) ?? 0) > 0; // it consumes something
    if (!hasFormula) continue;
    if (terminal.has(node)) continue; // it IS an output
    // reaches no terminal?
    const seen = new Set<string>();
    const q = [node];
    let hitsTerminal = false;
    while (q.length) {
      const cur = q.shift()!;
      if (terminal.has(cur)) { hitsTerminal = true; break; }
      for (const n of outEdges.get(cur) ?? []) if (!seen.has(n)) { seen.add(n); q.push(n); }
    }
    if (!hitsTerminal) {
      out.push({
        id: fid('disconnected', node),
        severity: 'warning',
        category: 'logical',
        sourceRef: node,
        explanation: `"${labelOf(node)}" computes a value but feeds into no output — dead-end calculation`,
        reachCount: 0,
        autoGenerated: true,
      });
    }
  }
  return out;
}

/** A formula that references a cell with no content (broken reference). */
function detectBrokenRefs(workbook: ParsedWorkbook, labelOf: (id: string) => string): DebugFinding[] {
  const out: DebugFinding[] = [];
  for (const sheet of workbook.sheets) {
    const populated = new Set(sheet.cells.map((c) => c.address.ref));
    for (const c of sheet.cells) {
      if (!c.formula) continue;
      const refs = [...c.formula.matchAll(/(?<![A-Za-z0-9_])\$?([A-Z]{1,3})\$?(\d+)/g)]
        .map((m) => `${m[1]}${m[2]}`)
        .filter((r) => !/^LOG|TRUE|FALSE/.test(r));
      for (const r of refs) {
        if (!populated.has(r)) {
          const cellId = `${sheet.name}!${c.address.ref}`;
          out.push({
            id: fid('brokenref', cellId, r),
            severity: 'critical',
            category: 'structural',
            sourceRef: cellId,
            explanation: `"${labelOf(cellId)}" references ${r}, which is empty — the formula will evaluate to 0 or error`,
            observedFormula: `=${c.formula}`,
            likelyCause: `Broken reference to empty cell ${r}`,
            autoGenerated: true,
            regressionTest: {
              name: `"${labelOf(cellId)}" resolves to a number`,
              category: 'structural',
              assertion: { type: 'is_numeric', left: cellId },
              description: `Regression guard: ${cellId} must not reference empty cell ${r}`,
            },
          });
          break; // one finding per formula is enough
        }
      }
    }
  }
  return out;
}

function findTerminals(graph: DependencyGraph): string[] {
  const hasOutgoing = new Set(graph.edges.map((e) => e.from));
  return graph.nodes.filter((n) => !hasOutgoing.has(n));
}
