import crypto from 'crypto';
import type { Model, DebugFinding, DependencyGraph } from './types.js';
import type { ParsedWorkbook } from './parser.js';
import { detectCycles } from './graph.js';

function fid(...parts: unknown[]): string {
  return crypto.createHash('sha1').update(parts.map(String).join('|')).digest('hex').slice(0, 12);
}

/** Analyze a model and produce classified findings (E7.1). */
export function analyzeFindings(model: Model, workbook: ParsedWorkbook | undefined): DebugFinding[] {
  const findings: DebugFinding[] = [];
  const graph: DependencyGraph = model.graph;

  // structural: circular dependencies
  const cycles = detectCycles(graph);
  for (const cycle of cycles) {
    findings.push({
      id: fid('cycle', cycle.join(',')),
      severity: 'critical',
      category: 'structural',
      sourceRef: cycle[0],
      explanation: `Circular dependency: ${cycle.join(' → ')} → ${cycle[0]}`,
      autoGenerated: true,
    });
  }

  // structural: external references (from discovery)
  if (model.discovery?.externalReferences > 0) {
    findings.push({
      id: fid('extrefs', model.discovery.externalReferences),
      severity: 'warning',
      category: 'structural',
      explanation: `${model.discovery.externalReferences} external reference(s) to other workbooks — these cannot be resolved deterministically`,
      autoGenerated: true,
    });
  }

  // Build reach map once (downstream output count per cell)
  const terminalSet = new Set(findTerminals(graph));
  const outEdges = new Map<string, string[]>();
  for (const e of graph.edges) {
    if (!outEdges.has(e.from)) outEdges.set(e.from, []);
    outEdges.get(e.from)!.push(e.to);
  }
  const reachCache = new Map<string, Set<string>>();
  const reachableOutputs = (start: string): Set<string> => {
    if (reachCache.has(start)) return reachCache.get(start)!;
    const seen = new Set<string>();
    const queue = [start];
    while (queue.length) {
      const cur = queue.shift()!;
      for (const next of outEdges.get(cur) ?? []) {
        if (seen.has(next)) continue;
        seen.add(next);
        queue.push(next);
      }
    }
    const outputs = new Set([...seen].filter((n) => terminalSet.has(n)));
    reachCache.set(start, outputs);
    return outputs;
  };

  // logical: dead inputs (parameters that reach no output)
  if (workbook) {
    for (const p of model.parameters) {
      const cellId = `${p.sourceCell.sheet}!${p.sourceCell.ref}`;
      const reach = reachableOutputs(cellId);
      if (reach.size === 0) {
        findings.push({
          id: fid('dead-input', cellId),
          severity: 'info',
          category: 'logical',
          sourceRef: cellId,
          explanation: `Input "${p.name}" does not affect any output — potential dead input`,
          reachCount: 0,
          autoGenerated: true,
        });
      }
    }
  }

  // consistency: same label resolved to different cells with differing formats
  if (workbook) {
    const byLabel = new Map<string, { cellId: string; format?: string }[]>();
    for (const o of model.outputs) {
      const cellId = `${o.sourceCell.sheet}!${o.sourceCell.ref}`;
      const key = o.name;
      if (!byLabel.has(key)) byLabel.set(key, []);
      byLabel.get(key)!.push({ cellId, format: o.format });
    }
    for (const [label, cells] of byLabel) {
      if (cells.length < 2) continue;
      const formats = new Set(cells.map((c) => c.format ?? 'General'));
      if (formats.size > 1) {
        findings.push({
          id: fid('fmt', label),
          severity: 'warning',
          category: 'consistency',
          sourceRef: cells[0].cellId,
          explanation: `Output "${label}" appears ${cells.length}× with inconsistent formats (${[...formats].join(', ')})`,
          autoGenerated: true,
        });
      }
    }
  }

  // coverage: outputs with no test coverage are surfaced at the API layer (needs test store)

  // Order: critical → warning → info
  const order = { critical: 0, warning: 1, info: 2 };
  findings.sort((a, b) => order[a.severity] - order[b.severity]);
  return findings;
}

function findTerminals(graph: DependencyGraph): string[] {
  const hasOutgoing = new Set(graph.edges.map((e) => e.from));
  return graph.nodes.filter((n) => !hasOutgoing.has(n));
}
