import type { Model, ModelDiff, ModelTestDefinition, DebugFinding } from './types.js';
import crypto from 'crypto';

function fid(...parts: unknown[]): string {
  return crypto.createHash('sha1').update(parts.map(String).join('|')).digest('hex').slice(0, 12);
}

/**
 * E10.2 — Advisory regression enforcement (Rule 7). When a model is re-imported
 * with a bugfix, at least one new test should target the changed cells. This is
 * advisory: it produces a warning finding, not a hard block.
 */
export function checkBugfixRegression(
  diff: ModelDiff,
  previousVersion: string,
  newTests: ModelTestDefinition[],   // tests created since the previous version
): DebugFinding | null {
  const changedCells = diff.entries
    .filter((e) => e.changeType !== 'added')
    .map((e) => e.path.replace(/^calculations\./, '').replace(/\.formula$/, ''));

  // A guarding test must reference a changed cell (in its assertion) and be new
  const guards = newTests.filter((t) => {
    const left = t.assertion?.left;
    if (typeof left !== 'string') return false;
    if (t.assertion.regressionFor === previousVersion) return true;
    return changedCells.some((cell) => left.includes(cell));
  });

  if (guards.length > 0) return null; // covered

  return {
    id: fid('bugfix-regression', previousVersion),
    severity: 'warning',
    category: 'coverage',
    explanation: `Bugfix re-import of ${previousVersion} changed ${changedCells.length} cell(s) but no new test guards them — add a regression test that would have caught the original defect (Rule 7)`,
    autoGenerated: true,
    reachCount: changedCells.length,
  };
}
