/** Core domain types for XLent model engine. */

export type CellAddress = { sheet: string; ref: string };

export type CellType = 'number' | 'string' | 'date' | 'boolean' | 'error' | 'blank';

export interface Cell {
  address: CellAddress;
  value: unknown;
  type: CellType;
  formula?: string;
  format?: string;
}

export type ParameterSource =
  | 'CLIENT_MODEL'
  | 'USER_OVERRIDE'
  | 'SYSTEM_DEFAULT'
  | 'EXTERNAL_DATA';

export interface Parameter {
  id: string;
  name: string;
  type: CellType;
  unit?: string;
  format?: string;
  currentValue: unknown;
  originalValue: unknown;
  allowedRange?: { min?: number; max?: number };
  sourceCell: CellAddress;
  source: ParameterSource;
  confidence: 'HIGH' | 'MEDIUM' | 'LOW';
  confirmed: boolean;
}

export interface Calculation {
  id: string;
  sourceCell: CellAddress;
  originalFormula: string;
  normalizedFormula?: string;
  dependencies: string[]; // cell refs
  downstreamOutputs: string[];
}

export interface Output {
  id: string;
  name: string;
  value: unknown;
  format?: string;
  sourceCell: CellAddress;
  dependsOn: string[]; // parameter IDs
  confidence: 'HIGH' | 'MEDIUM' | 'LOW';
  confirmed: boolean;
}

export interface DependencyEdge {
  from: string; // cell ref
  to: string; // cell ref
}

export interface DependencyGraph {
  nodes: string[];
  edges: DependencyEdge[];
}

export type CompatibilityStatus = 'VALID' | 'PARTIAL' | 'INVALID';

export interface CompatibilityIssue {
  type: 'unsupported_function' | 'external_reference' | 'circular_dependency' | 'vba' | 'error';
  cell?: CellAddress;
  detail: string;
  severity: 'error' | 'warning' | 'info';
}

export interface CompatibilityReport {
  status: CompatibilityStatus;
  supportedFormulas: number;
  totalFormulas: number;
  issues: CompatibilityIssue[];
}

// --- Debugging (E7) ---

export type FindingSeverity = 'critical' | 'warning' | 'info';
export type FindingCategory = 'structural' | 'logical' | 'consistency' | 'coverage' | 'intent';

export interface ImpactEstimate {
  outputId: string;
  outputName: string;
  observedValue: unknown;
  expectedValue: unknown;  // value if the defect were corrected
  delta: number | null;
  percentDelta: number | null;
}

/** Rule 7: a finding can be converted into a regression test. */
export interface RegressionTestPayload {
  name: string;
  category: 'structural' | 'mathematical' | 'business';
  assertion: { type: string; left: string; right?: unknown };
  description?: string;
}

export interface DebugFinding {
  id: string;
  severity: FindingSeverity;
  category: FindingCategory;
  sourceRef?: string;      // cellId e.g. 'Value Effect!B37'
  explanation: string;
  impact?: string;         // e.g. 'affects 4 outputs'
  reachCount?: number;     // downstream output count
  autoGenerated: boolean;

  // Constitution §22 / E7.4: richer defect detail
  expectedFormula?: string;   // what the pattern implies the formula should be
  observedFormula?: string;   // what is actually in the cell
  likelyCause?: string;       // inferred reason for the mismatch
  impactChain?: string[];     // ordered downstream path e.g. [Revenue, EBITDA, FCF, IRR]
  impactEstimates?: ImpactEstimate[]; // quantified per-output delta

  // Rule 7: one-click regression protection
  regressionTest?: RegressionTestPayload;
}

export interface ParameterImpactInfo {
  parameterId: string;
  name: string;
  reachCount: number;      // how many outputs this parameter reaches
  sensitivityRank?: number; // 1-based rank by total impact (if sensitivity run)
  dead: boolean;           // no downstream reach
}

// --- Model Contract (E8) ---

export interface DeclaredInput {
  name: string;
  unit?: string;
  description?: string;
  bounds?: { min?: number; max?: number };
}

export interface DeclaredOutput {
  name: string;
  unit?: string;
  meaning?: string;         // expected semantics, e.g. 'Recognized revenue'
  expectation?: string;     // e.g. 'non-negative', 'monotonic increasing'
}

export interface ContractRule {
  id: string;               // e.g. 'R001'
  expression: string;       // e.g. 'Revenue = Units Sold × ASP'
  description?: string;
  severity?: FindingSeverity; // default 'critical'
  scope?: string;           // e.g. 'All forecast periods'
}

export interface ContractInvariant {
  id: string;               // e.g. 'C001'
  expression: string;       // e.g. 'Debt >= 0'
  description?: string;
}

export interface ContractBehavior {
  id: string;               // e.g. 'B001'
  statement: string;        // e.g. 'Increasing ASP must not reduce Revenue when volume is constant'
  description?: string;
}

export interface ModelContract {
  purpose: string;
  declaredInputs: DeclaredInput[];
  declaredOutputs: DeclaredOutput[];
  invariants: ContractInvariant[];
  rules: ContractRule[];
  behaviors?: ContractBehavior[];
  version: string;
  /** authority: this contract is the highest-authority statement of intent */
}

export interface ModelDiscovery {
  workbookName: string;
  sheets: number;
  formulaCells: number;
  inputCandidates: number;
  outputCandidates: number;
  crossSheetReferences: number;
  externalReferences: number;
  namedRanges: number;
  unsupportedFunctions: number;
  circularDependencies: number;
  compatibility: CompatibilityStatus;
}

export type ModelStatus = 'draft' | 'sandbox' | 'validated' | 'approved' | 'published' | 'deprecated';

export interface Model {
  id: string;
  name: string;
  slug: string;
  semver: string;
  version: number;
  status: ModelStatus;
  createdAt: string;
  workbookName: string;
  parameters: Parameter[];
  calculations: Calculation[];
  outputs: Output[];
  graph: DependencyGraph;
  compatibility: CompatibilityReport;
  discovery: ModelDiscovery;
  contract?: ModelContract;
}

// --- Snapshots & Versioning (E2) ---

export interface Snapshot {
  id: string;
  modelId: string;
  semver: string;
  message?: string;
  checksum: string;
  createdAt: string;
  data: Model;
}

export type DiffChangeType = 'added' | 'removed' | 'modified';
export type DiffSemantics = 'semantic' | 'cosmetic';
export type SuggestedBump = 'patch' | 'minor' | 'major';

export interface DiffEntry {
  path: string;
  changeType: DiffChangeType;
  semantics: DiffSemantics;
  before?: unknown;
  after?: unknown;
  description: string;
}

export interface ModelDiff {
  fromVersion: string;
  toVersion: string;
  entries: DiffEntry[];
  suggestedBump: SuggestedBump;
  summary: string;
}

export interface ScenarioOverride {
  parameterId: string;
  value: unknown;
}

export interface Scenario {
  id: string;
  modelId: string;
  modelVersion: number;
  name: string;
  overrides: ScenarioOverride[];
  results: Record<string, unknown>; // output id → value
  createdAt: string;
}

export interface ComparisonRow {
  outputId: string;
  outputName: string;
  baseline: unknown;
  scenario: unknown;
  delta: number | null;
  percentDelta: number | null;
}

export interface Comparison {
  modelId: string;
  baselineScenarioId: string | null; // null = model defaults
  comparedScenarioId: string;
  rows: ComparisonRow[];
}

export interface Provenance {
  parameterId: string;
  source: ParameterSource;
  workbook?: string;
  sheet?: string;
  cell?: string;
  modified: boolean;
  modifiedBy?: string;
  modifiedAt?: string;
}

export interface DeliverableItem {
  id: string;
  name: string;
  value: unknown;
  sourceCell: string;
  confidence: 'HIGH' | 'MEDIUM' | 'LOW';
}

export interface Deliverable {
  id: string;
  modelId: string;
  modelName: string;
  modelVersion: number;
  executedAt: string;
  outputs: DeliverableItem[];
  parameters: DeliverableItem[];
  overridesApplied: ScenarioOverride[];
  compatibility: CompatibilityReport;
}

// --- Model Testing (E1) ---

export type TestCategory = 'structural' | 'mathematical' | 'business';

export type AssertionType =
  | 'equals'
  | 'gt'
  | 'lt'
  | 'gte'
  | 'lte'
  | 'between'
  | 'balance'
  | 'non_negative'
  | 'is_numeric'
  | 'custom';

export interface TestAssertion {
  type: AssertionType;
  left: string;   // output ID or cell ref to check
  right?: unknown; // expected value or upper bound
  rightB?: unknown; // lower bound for 'between'
  tolerance?: number;
}

export interface ModelTestDefinition {
  id: string;
  modelId: string;
  name: string;
  category: TestCategory;
  assertion: TestAssertion;
  description?: string;
  autoGenerated: boolean;
}

export type TestStatus = 'pass' | 'fail' | 'error' | 'skip';

export interface ModelTestResult {
  testId: string;
  name: string;
  category: TestCategory;
  status: TestStatus;
  actual?: unknown;
  expected?: unknown;
  message?: string;
  executedAt: string;
}

// --- Evidence Records (E1) ---

export interface EvidenceRecord {
  id: string;
  modelId: string;
  modelVersion: number;
  executedAt: string;
  inputs: Record<string, unknown>;
  overrides: ScenarioOverride[];
  scenario?: string;
  outputs: Record<string, unknown>;
  tests: ModelTestResult[];
  allTestsPass: boolean;
  checksum: string;
  reproducible: boolean;
  executedBy?: string;
  purpose?: 'scenario_run' | 'publish_gate' | 'delivery' | 'manual';
}

// --- Model Package (E5) ---

export type AssuranceStatus = 'pass' | 'conditional' | 'fail';

export interface Finding {
  id: string;
  type: 'structural' | 'mathematical' | 'business' | 'compatibility';
  severity: 'critical' | 'warning' | 'info';
  message: string;
  detail?: string;
}

export interface AssuranceSummary {
  overallStatus: AssuranceStatus;
  totalTests: number;
  passed: number;
  failed: number;
  errors: number;
  skipped: number;
  findings: Finding[];
  evidenceId?: string;
}

export interface ModelPackage {
  id: string;
  modelId: string;
  slug: string;
  semver: string;
  name: string;
  executedAt: string;
  deliverable: Deliverable;
  assurance: AssuranceSummary;
  evidence?: EvidenceRecord;
  discovery: ModelDiscovery;
  compatibility: CompatibilityReport;
}
