import { describe, expect, it } from 'vitest';
import * as XLSX from 'xlsx';
import { buildGraph } from '../graph.js';
import { previewMutation } from '../mutation/index.js';
import { parseWorkbook } from '../parser.js';
import type { Model } from '../types.js';

function buildFixture(): { model: Model; workbook: ReturnType<typeof parseWorkbook> } {
  const source = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(source, XLSX.utils.aoa_to_sheet([[10], [{ t: 'n', f: 'A1*2' }]]), 'Model');
  const workbook = parseWorkbook(Buffer.from(XLSX.write(source, { type: 'buffer', bookType: 'xlsx' })), 'mutation.xlsx');
  const graph = buildGraph(workbook);
  const model: Model = {
    id: 'model-1',
    name: 'Mutation fixture',
    slug: 'mutation-fixture',
    semver: '1.0.0',
    version: 1,
    status: 'draft',
    createdAt: '2026-08-07T00:00:00.000Z',
    workbookName: 'mutation.xlsx',
    parameters: [{
      id: 'revenue',
      name: 'Revenue',
      type: 'number',
      currentValue: 10,
      originalValue: 10,
      allowedRange: { min: 0, max: 100 },
      sourceCell: { sheet: 'Model', ref: 'A1' },
      source: 'CLIENT_MODEL',
      confidence: 'HIGH',
      confirmed: true,
    }],
    calculations: [],
    outputs: [{
      id: 'double-revenue',
      name: 'Double Revenue',
      value: 20,
      sourceCell: { sheet: 'Model', ref: 'A2' },
      dependsOn: ['revenue'],
      confidence: 'HIGH',
      confirmed: true,
    }],
    graph,
    compatibility: { status: 'VALID', supportedFormulas: 1, totalFormulas: 1, issues: [] },
    discovery: { workbookName: 'mutation.xlsx', sheets: 1, formulaCells: 1, inputCandidates: 1, outputCandidates: 1, crossSheetReferences: 0, externalReferences: 0, namedRanges: 0, unsupportedFunctions: 0, circularDependencies: 0, compatibility: 'VALID' },
  };
  return { model, workbook };
}

describe('previewMutation', () => {
  it('previews a deterministic parameter mutation without changing the source model', () => {
    const { model, workbook } = buildFixture();
    const preview = previewMutation(model, workbook, {
      actor: { id: 'user-1', type: 'human' },
      rationale: 'Test the governed mutation path',
      operations: [{ type: 'setParameterValue', parameterId: 'revenue', value: 25 }],
    }, [{
      id: 'test-1',
      modelId: model.id,
      name: 'Mutation output is recalculated',
      category: 'business',
      assertion: { type: 'equals', left: 'double-revenue', right: 50 },
      autoGenerated: false,
    }]);

    expect(preview.valid).toBe(true);
    expect(preview.proposedModel?.parameters[0].currentValue).toBe(25);
    expect(preview.proposedModel?.outputs[0].value).toBe(50);
    expect(preview.proposedModel?.semver).toBe('1.1.0');
    expect(preview.previewId).toMatch(/^[a-f0-9]{64}$/);
    expect(preview.evidenceRefs).toEqual([{ kind: 'preview', checksum: preview.previewId }]);
    expect(preview.affectedComponents).toEqual(['Model!A1', 'Model!A2']);
    expect(preview.affectedOutputs).toEqual(['double-revenue']);
    expect(preview.testResults).toEqual([
      expect.objectContaining({ name: 'Mutation output is recalculated', status: 'pass', actual: 50 }),
    ]);
    expect(preview.allTestsPass).toBe(true);
    expect(preview.contractFindings).toEqual([]);
    expect(preview.diff?.entries.map((entry) => entry.path)).toEqual([
      'parameters.Revenue.value',
      'outputs.Double Revenue.value',
    ]);
    expect(model.parameters[0].currentValue).toBe(10);
    expect(model.outputs[0].value).toBe(20);
    expect(model.semver).toBe('1.0.0');
  });

  it('rejects the entire batch when a value violates the parameter contract', () => {
    const { model, workbook } = buildFixture();
    const preview = previewMutation(model, workbook, {
      actor: { id: 'agent-1', type: 'agent' },
      rationale: 'Invalid proposal',
      operations: [{ type: 'setParameterValue', parameterId: 'revenue', value: 101 }],
    });

    expect(preview.valid).toBe(false);
    expect(preview.previewId).toBeUndefined();
    expect(preview.proposedModel).toBeUndefined();
    expect(preview.evidenceRefs).toEqual([]);
    expect(preview.allTestsPass).toBe(false);
    expect(preview.validationIssues).toEqual([expect.objectContaining({ code: 'outside_allowed_range' })]);
    expect(model.parameters[0].currentValue).toBe(10);
  });

  it('renames a parameter across model intent and name-based tests without changing cell identity', () => {
    const { model, workbook } = buildFixture();
    model.contract = {
      purpose: 'Test rename propagation',
      declaredInputs: [{ name: 'Revenue' }],
      declaredOutputs: [{ name: 'Double Revenue' }],
      invariants: [{ id: 'inv-1', expression: 'Revenue >= 0' }],
      rules: [{ id: 'rule-1', expression: 'Double Revenue = Revenue * 2' }],
      behaviors: [{ id: 'behavior-1', statement: 'Increasing Revenue increases Double Revenue' }],
      version: '1.0.0',
    };
    const originalGraph = structuredClone(model.graph);

    const preview = previewMutation(model, workbook, {
      actor: { id: 'user-1', type: 'human' },
      rationale: 'Use the contract-approved input name',
      operations: [{ type: 'renameParameter', parameterId: 'revenue', name: 'Sales' }],
    }, [{
      id: 'test-rename',
      modelId: model.id,
      name: 'Input remains non-negative',
      category: 'business',
      assertion: { type: 'non_negative', left: 'Revenue' },
      autoGenerated: false,
    }]);

    expect(preview.valid).toBe(true);
    expect(preview.proposedModel?.parameters[0].name).toBe('Sales');
    expect(preview.proposedModel?.contract?.declaredInputs[0].name).toBe('Sales');
    expect(preview.proposedModel?.contract?.invariants[0].expression).toBe('Sales >= 0');
    expect(preview.proposedModel?.contract?.rules[0].expression).toBe('Double Revenue = Sales * 2');
    expect(preview.proposedModel?.contract?.behaviors?.[0].statement).toBe('Increasing Sales increases Double Revenue');
    expect(preview.proposedTests?.[0].assertion.left).toBe('Sales');
    expect(preview.testResults).toEqual([expect.objectContaining({ status: 'pass', actual: 10 })]);
    expect(preview.proposedModel?.graph).toEqual(originalGraph);
    expect(preview.proposedModel?.outputs[0].value).toBe(20);
    expect(preview.diff?.entries).toEqual([
      expect.objectContaining({ path: 'parameters.Revenue.name', before: 'Revenue', after: 'Sales' }),
    ]);
    expect(model.parameters[0].name).toBe('Revenue');
    expect(model.contract.declaredInputs[0].name).toBe('Revenue');
  });

  it('rejects duplicate final names across an atomic rename batch', () => {
    const { model, workbook } = buildFixture();
    model.parameters.push({ ...model.parameters[0], id: 'cost', name: 'Cost', sourceCell: { sheet: 'Model', ref: 'A3' } });

    const preview = previewMutation(model, workbook, {
      actor: { id: 'user-1', type: 'human' },
      rationale: 'Attempt an ambiguous rename',
      operations: [
        { type: 'renameParameter', parameterId: 'revenue', name: 'Value' },
        { type: 'renameParameter', parameterId: 'cost', name: 'Value' },
      ],
    });

    expect(preview.valid).toBe(false);
    expect(preview.validationIssues).toEqual(expect.arrayContaining([
      expect.objectContaining({ code: 'duplicate_name' }),
    ]));
  });
});