import { describe, expect, it } from 'vitest';
import * as XLSX from 'xlsx';
import { buildGraph } from '../graph.js';
import { previewMutation } from '../mutation/index.js';
import { parseWorkbook } from '../parser.js';
import type { Model } from '../types.js';

function buildFixture(): { model: Model; workbook: ReturnType<typeof parseWorkbook> } {
  const source = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(source, XLSX.utils.aoa_to_sheet([[10], [{ t: 'n', f: 'A1*2' }]]), 'Model');
  const workbook = parseWorkbook(Buffer.from(XLSX.write(source, { type: 'buffer', bookType: 'xlsx' })), 'mutation.xlsx');
  const graph = buildGraph(workbook);
  const model: Model = {
    id: 'model-1',
    name: 'Mutation fixture',
    slug: 'mutation-fixture',
    semver: '1.0.0',
    version: 1,
    status: 'draft',
    createdAt: '2026-08-07T00:00:00.000Z',
    workbookName: 'mutation.xlsx',
    parameters: [{
      id: 'revenue',
      name: 'Revenue',
      type: 'number',
      currentValue: 10,
      originalValue: 10,
      allowedRange: { min: 0, max: 100 },
      sourceCell: { sheet: 'Model', ref: 'A1' },
      source: 'CLIENT_MODEL',
      confidence: 'HIGH',
      confirmed: true,
    }],
    calculations: [],
    outputs: [{
      id: 'double-revenue',
      name: 'Double Revenue',
      value: 20,
      sourceCell: { sheet: 'Model', ref: 'A2' },
      dependsOn: ['revenue'],
      confidence: 'HIGH',
      confirmed: true,
    }],
    graph,
    compatibility: { status: 'VALID', supportedFormulas: 1, totalFormulas: 1, issues: [] },
    discovery: { workbookName: 'mutation.xlsx', sheets: 1, formulaCells: 1, inputCandidates: 1, outputCandidates: 1, crossSheetReferences: 0, externalReferences: 0, namedRanges: 0, unsupportedFunctions: 0, circularDependencies: 0, compatibility: 'VALID' },
  };
  return { model, workbook };
}

describe('previewMutation', () => {
  it('previews a deterministic parameter mutation without changing the source model', () => {
    const { model, workbook } = buildFixture();
    const preview = previewMutation(model, workbook, {
      actor: { id: 'user-1', type: 'human' },
      rationale: 'Test the governed mutation path',
      operations: [{ type: 'setParameterValue', parameterId: 'revenue', value: 25 }],
    }, [{
      id: 'test-1',
      modelId: model.id,
      name: 'Mutation output is recalculated',
      category: 'business',
      assertion: { type: 'equals', left: 'double-revenue', right: 50 },
      autoGenerated: false,
    }]);

    expect(preview.valid).toBe(true);
    expect(preview.proposedModel?.parameters[0].currentValue).toBe(25);
    expect(preview.proposedModel?.outputs[0].value).toBe(50);
    expect(preview.proposedModel?.semver).toBe('1.1.0');
    expect(preview.previewId).toMatch(/^[a-f0-9]{64}$/);
    expect(preview.evidenceRefs).toEqual([{ kind: 'preview', checksum: preview.previewId }]);
    expect(preview.affectedComponents).toEqual(['Model!A1', 'Model!A2']);
    expect(preview.affectedOutputs).toEqual(['double-revenue']);
    expect(preview.testResults).toEqual([
      expect.objectContaining({ name: 'Mutation output is recalculated', status: 'pass', actual: 50 }),
    ]);
    expect(preview.allTestsPass).toBe(true);
    expect(preview.contractFindings).toEqual([]);
    expect(preview.diff?.entries.map((entry) => entry.path)).toEqual([
      'parameters.Revenue.value',
      'outputs.Double Revenue.value',
    ]);
    expect(model.parameters[0].currentValue).toBe(10);
    expect(model.outputs[0].value).toBe(20);
    expect(model.semver).toBe('1.0.0');
  });

  it('rejects the entire batch when a value violates the parameter contract', () => {
    const { model, workbook } = buildFixture();
    const preview = previewMutation(model, workbook, {
      actor: { id: 'agent-1', type: 'agent' },
      rationale: 'Invalid proposal',
      operations: [{ type: 'setParameterValue', parameterId: 'revenue', value: 101 }],
    });

    expect(preview.valid).toBe(false);
    expect(preview.previewId).toBeUndefined();
    expect(preview.proposedModel).toBeUndefined();
    expect(preview.evidenceRefs).toEqual([]);
    expect(preview.allTestsPass).toBe(false);
    expect(preview.validationIssues).toEqual([expect.objectContaining({ code: 'outside_allowed_range' })]);
    expect(model.parameters[0].currentValue).toBe(10);
  });

  it('renames a parameter across model intent and name-based tests without changing cell identity', () => {
    const { model, workbook } = buildFixture();
    model.contract = {
      purpose: 'Test rename propagation',
      declaredInputs: [{ name: 'Revenue' }],
      declaredOutputs: [{ name: 'Double Revenue' }],
      invariants: [{ id: 'inv-1', expression: 'Revenue >= 0' }],
      rules: [{ id: 'rule-1', expression: 'Double Revenue = Revenue * 2' }],
      behaviors: [{ id: 'behavior-1', statement: 'Increasing Revenue increases Double Revenue' }],
      version: '1.0.0',
    };
    const originalGraph = structuredClone(model.graph);

    const preview = previewMutation(model, workbook, {
      actor: { id: 'user-1', type: 'human' },
      rationale: 'Use the contract-approved input name',
      operations: [{ type: 'renameParameter', parameterId: 'revenue', name: 'Sales' }],
    }, [{
      id: 'test-rename',
      modelId: model.id,
      name: 'Input remains non-negative',
      category: 'business',
      assertion: { type: 'non_negative', left: 'Revenue' },
      autoGenerated: false,
    }]);

    expect(preview.valid).toBe(true);
    expect(preview.proposedModel?.parameters[0].name).toBe('Sales');
    expect(preview.proposedModel?.contract?.declaredInputs[0].name).toBe('Sales');
    expect(preview.proposedModel?.contract?.invariants[0].expression).toBe('Sales >= 0');
    expect(preview.proposedModel?.contract?.rules[0].expression).toBe('Double Revenue = Sales * 2');
    expect(preview.proposedModel?.contract?.behaviors?.[0].statement).toBe('Increasing Sales increases Double Revenue');
    expect(preview.proposedTests?.[0].assertion.left).toBe('Sales');
    expect(preview.testResults).toEqual([expect.objectContaining({ status: 'pass', actual: 10 })]);
    expect(preview.proposedModel?.graph).toEqual(originalGraph);
    expect(preview.proposedModel?.outputs[0].value).toBe(20);
    expect(preview.diff?.entries).toEqual([
      expect.objectContaining({ path: 'parameters.Revenue.name', before: 'Revenue', after: 'Sales' }),
    ]);
    expect(model.parameters[0].name).toBe('Revenue');
    expect(model.contract.declaredInputs[0].name).toBe('Revenue');
  });

  it('rejects duplicate final names across an atomic rename batch', () => {
    const { model, workbook } = buildFixture();
    model.parameters.push({ ...model.parameters[0], id: 'cost', name: 'Cost', sourceCell: { sheet: 'Model', ref: 'A3' } });

    const preview = previewMutation(model, workbook, {
      actor: { id: 'user-1', type: 'human' },
      rationale: 'Attempt an ambiguous rename',
      operations: [
        { type: 'renameParameter', parameterId: 'revenue', name: 'Value' },
        { type: 'renameParameter', parameterId: 'cost', name: 'Value' },
      ],
    });

    expect(preview.valid).toBe(false);
    expect(preview.validationIssues).toEqual(expect.arrayContaining([
      expect.objectContaining({ code: 'duplicate_name' }),
    ]));
  });

  it('removes an isolated parameter and its graph node without changing outputs', () => {
    const { model, workbook } = buildFixture();
    model.parameters.push({ ...model.parameters[0], id: 'memo', name: 'Unused Memo', sourceCell: { sheet: 'Model', ref: 'A3' } });
    model.graph.nodes.push('Model!A3');

    const preview = previewMutation(model, workbook, {
      actor: { id: 'user-1', type: 'human' },
      rationale: 'Remove a confirmed unused input',
      operations: [{ type: 'removeParameter', parameterId: 'memo' }],
    });

    expect(preview.valid).toBe(true);
    expect(preview.proposedModel?.parameters.map((parameter) => parameter.id)).toEqual(['revenue']);
    expect(preview.proposedModel?.graph.nodes).not.toContain('Model!A3');
    expect(preview.proposedModel?.outputs[0].value).toBe(20);
    expect(preview.proposedModel?.semver).toBe('2.0.0');
    expect(preview.diff?.entries).toEqual([
      expect.objectContaining({ path: 'parameters.Unused Memo', changeType: 'removed' }),
    ]);
    expect(model.parameters.map((parameter) => parameter.id)).toEqual(['revenue', 'memo']);
  });

  it('blocks removal when a parameter has computational consumers', () => {
    const { model, workbook } = buildFixture();

    const preview = previewMutation(model, workbook, {
      actor: { id: 'user-1', type: 'human' },
      rationale: 'Attempt to remove a consumed input',
      operations: [{ type: 'removeParameter', parameterId: 'revenue' }],
    });

    expect(preview.valid).toBe(false);
    expect(preview.validationIssues).toEqual([
      expect.objectContaining({ code: 'parameter_has_consumers' }),
    ]);
  });

  it('blocks removal while contract or test intent references the parameter', () => {
    const { model, workbook } = buildFixture();
    const memo = { ...model.parameters[0], id: 'memo', name: 'Unused Memo', sourceCell: { sheet: 'Model', ref: 'A3' } };
    model.parameters.push(memo);
    model.graph.nodes.push('Model!A3');
    model.contract = {
      purpose: 'Retain governed intent',
      declaredInputs: [{ name: memo.name }],
      declaredOutputs: [],
      invariants: [],
      rules: [],
      version: '1.0.0',
    };

    const preview = previewMutation(model, workbook, {
      actor: { id: 'user-1', type: 'human' },
      rationale: 'Attempt to remove referenced intent',
      operations: [{ type: 'removeParameter', parameterId: memo.id }],
    }, [{
      id: 'memo-test',
      modelId: model.id,
      name: 'Memo remains numeric',
      category: 'business',
      assertion: { type: 'is_numeric', left: memo.name },
      autoGenerated: false,
    }]);

    expect(preview.valid).toBe(false);
    expect(preview.validationIssues).toEqual(expect.arrayContaining([
      expect.objectContaining({ code: 'parameter_has_contract_refs' }),
      expect.objectContaining({ code: 'parameter_has_test_refs' }),
    ]));
  });

  it('reorders parameters without changing graph identity or execution', () => {
    const { model, workbook } = buildFixture();
    model.parameters.push({ ...model.parameters[0], id: 'cost', name: 'Cost', sourceCell: { sheet: 'Model', ref: 'A3' } });
    const originalGraph = structuredClone(model.graph);

    const preview = previewMutation(model, workbook, {
      actor: { id: 'user-1', type: 'human' },
      rationale: 'Put cost assumptions before revenue assumptions',
      operations: [{ type: 'moveParameter', parameterId: 'cost', toIndex: 0 }],
    });

    expect(preview.valid).toBe(true);
    expect(preview.proposedModel?.parameters.map((parameter) => parameter.id)).toEqual(['cost', 'revenue']);
    expect(preview.proposedModel?.graph).toEqual(originalGraph);
    expect(preview.proposedModel?.outputs[0].value).toBe(20);
    expect(preview.proposedModel?.semver).toBe('1.0.1');
    expect(preview.affectedComponents).toEqual([]);
    expect(preview.affectedOutputs).toEqual([]);
    expect(preview.diff?.entries).toEqual([
      expect.objectContaining({ path: 'parameters.order', semantics: 'cosmetic' }),
    ]);
    expect(model.parameters.map((parameter) => parameter.id)).toEqual(['revenue', 'cost']);
  });

  it('renames an output across contract intent and name-based tests without changing identity', () => {
    const { model, workbook } = buildFixture();
    model.contract = {
      purpose: 'Test output rename propagation',
      declaredInputs: [{ name: 'Revenue' }],
      declaredOutputs: [{ name: 'Double Revenue' }],
      invariants: [],
      rules: [{ id: 'rule-1', expression: 'Double Revenue = Revenue * 2' }],
      version: '1.0.0',
    };
    const originalGraph = structuredClone(model.graph);

    const preview = previewMutation(model, workbook, {
      actor: { id: 'user-1', type: 'human' },
      rationale: 'Use the approved output name',
      operations: [{ type: 'renameOutput', outputId: 'double-revenue', name: 'Gross Revenue' }],
    }, [{
      id: 'output-test',
      modelId: model.id,
      name: 'Output remains non-negative',
      category: 'business',
      assertion: { type: 'non_negative', left: 'Double Revenue' },
      autoGenerated: false,
    }]);

    expect(preview.valid).toBe(true);
    expect(preview.proposedModel?.outputs[0]).toEqual(expect.objectContaining({ id: 'double-revenue', name: 'Gross Revenue', value: 20 }));
    expect(preview.proposedModel?.contract?.declaredOutputs[0].name).toBe('Gross Revenue');
    expect(preview.proposedModel?.contract?.rules[0].expression).toBe('Gross Revenue = Revenue * 2');
    expect(preview.proposedTests?.[0].assertion.left).toBe('Gross Revenue');
    expect(preview.testResults).toEqual([expect.objectContaining({ status: 'pass', actual: 20 })]);
    expect(preview.proposedModel?.graph).toEqual(originalGraph);
    expect(preview.diff?.entries).toEqual([
      expect.objectContaining({ path: 'outputs.Double Revenue.name', before: 'Double Revenue', after: 'Gross Revenue' }),
    ]);
    expect(model.outputs[0].name).toBe('Double Revenue');
  });

  it('reorders outputs without changing graph identity or execution', () => {
    const { model, workbook } = buildFixture();
    model.outputs.push({ ...model.outputs[0], id: 'reported-revenue', name: 'Reported Revenue' });
    const originalGraph = structuredClone(model.graph);

    const preview = previewMutation(model, workbook, {
      actor: { id: 'user-1', type: 'human' },
      rationale: 'Put reported revenue before the derived output',
      operations: [{ type: 'moveOutput', outputId: 'reported-revenue', toIndex: 0 }],
    });

    expect(preview.valid).toBe(true);
    expect(preview.proposedModel?.outputs.map((output) => output.id)).toEqual(['reported-revenue', 'double-revenue']);
    expect(preview.proposedModel?.outputs.map((output) => output.value)).toEqual([20, 20]);
    expect(preview.proposedModel?.graph).toEqual(originalGraph);
    expect(preview.proposedModel?.semver).toBe('1.0.1');
    expect(preview.affectedComponents).toEqual([]);
    expect(preview.affectedOutputs).toEqual([]);
    expect(preview.diff?.entries).toEqual([
      expect.objectContaining({ path: 'outputs.order', semantics: 'cosmetic' }),
    ]);
  });

  it('removes an output declaration without removing its calculation or graph node', () => {
    const { model, workbook } = buildFixture();
    const originalGraph = structuredClone(model.graph);

    const preview = previewMutation(model, workbook, {
      actor: { id: 'user-1', type: 'human' },
      rationale: 'Remove an output that is no longer part of the public model surface',
      operations: [{ type: 'removeOutput', outputId: 'double-revenue' }],
    });

    expect(preview.valid).toBe(true);
    expect(preview.proposedModel?.outputs).toEqual([]);
    expect(preview.proposedModel?.calculations).toEqual(model.calculations);
    expect(preview.proposedModel?.graph).toEqual(originalGraph);
    expect(preview.proposedModel?.semver).toBe('2.0.0');
    expect(preview.affectedComponents).toEqual(['Model!A2']);
    expect(preview.affectedOutputs).toEqual(['double-revenue']);
    expect(preview.diff?.entries).toEqual([
      expect.objectContaining({ path: 'outputs.Double Revenue', changeType: 'removed' }),
    ]);
    expect(model.outputs.map((output) => output.id)).toEqual(['double-revenue']);
  });

  it('blocks output removal while contract or test intent references it', () => {
    const { model, workbook } = buildFixture();
    model.contract = {
      purpose: 'Retain governed output intent',
      declaredInputs: [],
      declaredOutputs: [{ name: 'Double Revenue' }],
      invariants: [],
      rules: [],
      version: '1.0.0',
    };

    const preview = previewMutation(model, workbook, {
      actor: { id: 'user-1', type: 'human' },
      rationale: 'Attempt to remove referenced output intent',
      operations: [{ type: 'removeOutput', outputId: 'double-revenue' }],
    }, [{
      id: 'output-test',
      modelId: model.id,
      name: 'Output remains numeric',
      category: 'business',
      assertion: { type: 'is_numeric', left: 'Double Revenue' },
      autoGenerated: false,
    }]);

    expect(preview.valid).toBe(false);
    expect(preview.validationIssues).toEqual(expect.arrayContaining([
      expect.objectContaining({ code: 'output_has_contract_refs' }),
      expect.objectContaining({ code: 'output_has_test_refs' }),
    ]));
  });

  it('promotes an existing formula component to an output without changing the graph', () => {
    const source = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(source, XLSX.utils.aoa_to_sheet([[10], [{ t: 'n', f: 'A1*2' }], [{ t: 'n', f: 'A2+5' }]]), 'Model');
    const workbook = parseWorkbook(Buffer.from(XLSX.write(source, { type: 'buffer', bookType: 'xlsx' })), 'promotion.xlsx');
    const { model } = buildFixture();
    model.graph = buildGraph(workbook);
    model.outputs[0] = { ...model.outputs[0], id: 'final-revenue', name: 'Final Revenue', value: 25, sourceCell: { sheet: 'Model', ref: 'A3' } };
    const originalGraph = structuredClone(model.graph);

    const preview = previewMutation(model, workbook, {
      actor: { id: 'user-1', type: 'human' },
      rationale: 'Expose an approved intermediate result',
      operations: [{ type: 'addOutput', outputId: 'double-revenue', name: 'Double Revenue', sourceCell: { sheet: 'Model', ref: 'A2' } }],
    });

    expect(preview.valid).toBe(true);
    expect(preview.proposedModel?.outputs[1]).toEqual(expect.objectContaining({
      id: 'double-revenue',
      name: 'Double Revenue',
      value: 20,
      dependsOn: ['revenue'],
      confirmed: true,
    }));
    expect(preview.proposedModel?.graph).toEqual(originalGraph);
    expect(preview.proposedModel?.semver).toBe('1.1.0');
    expect(preview.affectedOutputs).toEqual(expect.arrayContaining(['final-revenue', 'double-revenue']));
    expect(preview.diff?.entries).toEqual([
      expect.objectContaining({ path: 'outputs.Double Revenue', changeType: 'added' }),
    ]);
    expect(model.outputs).toHaveLength(1);

    const duplicateSource = previewMutation(model, workbook, {
      actor: { id: 'user-1', type: 'human' },
      rationale: 'Attempt duplicate output aliases',
      operations: [
        { type: 'addOutput', outputId: 'double-revenue', name: 'Double Revenue', sourceCell: { sheet: 'Model', ref: 'A2' } },
        { type: 'addOutput', outputId: 'double-revenue-copy', name: 'Double Revenue Copy', sourceCell: { sheet: 'Model', ref: 'A2' } },
      ],
    });
    expect(duplicateSource.valid).toBe(false);
    expect(duplicateSource.validationIssues).toEqual(expect.arrayContaining([
      expect.objectContaining({ code: 'output_source_already_exposed' }),
    ]));
  });

  it('rejects output promotion from a non-formula or already exposed component', () => {
    const { model, workbook } = buildFixture();
    const preview = previewMutation(model, workbook, {
      actor: { id: 'user-1', type: 'human' },
      rationale: 'Attempt invalid promotions',
      operations: [
        { type: 'addOutput', outputId: 'raw-output', name: 'Raw Revenue', sourceCell: { sheet: 'Model', ref: 'A1' } },
        { type: 'addOutput', outputId: 'duplicate-output', name: 'Duplicate Revenue', sourceCell: { sheet: 'Model', ref: 'A2' } },
      ],
    });

    expect(preview.valid).toBe(false);
    expect(preview.validationIssues).toEqual(expect.arrayContaining([
      expect.objectContaining({ code: 'output_source_not_formula' }),
      expect.objectContaining({ code: 'output_source_already_exposed' }),
    ]));
  });

  it('adds an isolated native parameter with a deterministic virtual root node', () => {
    const { model, workbook } = buildFixture();
    const originalOutput = structuredClone(model.outputs[0]);

    const preview = previewMutation(model, workbook, {
      actor: { id: 'user-1', type: 'human' },
      rationale: 'Introduce a governed native assumption',
      operations: [{ type: 'addParameter', parameterId: 'tax-rate', name: 'Tax Rate', parameterType: 'number', value: 0.21 }],
    });

    expect(preview.valid).toBe(true);
    expect(preview.proposedModel?.parameters.at(-1)).toEqual(expect.objectContaining({
      id: 'tax-rate',
      name: 'Tax Rate',
      type: 'number',
      currentValue: 0.21,
      sourceCell: { sheet: 'XLent Inputs', ref: 'A1' },
      source: 'USER_OVERRIDE',
      confidence: 'HIGH',
      confirmed: true,
    }));
    expect(preview.proposedModel?.graph.nodes).toContain('XLent Inputs!A1');
    expect(preview.proposedModel?.graph.edges).toEqual(model.graph.edges);
    expect(preview.proposedModel?.outputs[0]).toEqual(originalOutput);
    expect(preview.proposedModel?.semver).toBe('1.1.0');
    expect(preview.affectedComponents).toEqual(['XLent Inputs!A1']);
    expect(preview.affectedOutputs).toEqual([]);
    expect(preview.diff?.entries).toEqual([expect.objectContaining({ path: 'parameters.Tax Rate', changeType: 'added' })]);
    expect(model.parameters).toHaveLength(1);
  });

  it('assigns sequential virtual cells to multiple native inputs in one batch', () => {
    const { model, workbook } = buildFixture();

    const preview = previewMutation(model, workbook, {
      actor: { id: 'user-1', type: 'human' },
      rationale: 'Introduce two governed native assumptions',
      operations: [
        { type: 'addParameter', parameterId: 'tax-rate', name: 'Tax Rate', parameterType: 'number', value: 0.21 },
        { type: 'addParameter', parameterId: 'exit-year', name: 'Exit Year', parameterType: 'number', value: 2030 },
      ],
    });

    expect(preview.valid).toBe(true);
    expect(preview.proposedModel?.parameters.map((parameter) => parameter.sourceCell)).toEqual(expect.arrayContaining([
      { sheet: 'XLent Inputs', ref: 'A1' },
      { sheet: 'XLent Inputs', ref: 'A2' },
    ]));
    expect(preview.affectedComponents).toEqual(['XLent Inputs!A1', 'XLent Inputs!A2']);
  });

  it('rejects a native input with a duplicate name or mismatched type', () => {
    const { model, workbook } = buildFixture();

    const preview = previewMutation(model, workbook, {
      actor: { id: 'user-1', type: 'human' },
      rationale: 'Attempt invalid native inputs',
      operations: [
        { type: 'addParameter', parameterId: 'dup', name: 'Revenue', parameterType: 'number', value: 1 },
        { type: 'addParameter', parameterId: 'bad-type', name: 'Flag', parameterType: 'number', value: 'yes' },
      ],
    });

    expect(preview.valid).toBe(false);
    expect(preview.validationIssues).toEqual(expect.arrayContaining([
      expect.objectContaining({ code: 'duplicate_name' }),
      expect.objectContaining({ code: 'invalid_type' }),
    ]));
  });

  it('edits a formula through the canonical mutation path and recomputes outputs', () => {
    const { model, workbook } = buildFixture();
    model.calculations = [{
      id: 'calc-a2',
      sourceCell: { sheet: 'Model', ref: 'A2' },
      originalFormula: 'A1*2',
      dependencies: ['Model!A1'],
      downstreamOutputs: [],
    }];

    const preview = previewMutation(model, workbook, {
      actor: { id: 'user-1', type: 'human' },
      rationale: 'Triple the revenue multiplier',
      operations: [{ type: 'setCellFormula', sourceCell: { sheet: 'Model', ref: 'A2' }, formula: '=A1*3' }],
    });

    expect(preview.valid).toBe(true);
    expect(preview.proposedModel?.outputs[0].value).toBe(30);
    expect(preview.proposedModel?.calculations[0]).toEqual(expect.objectContaining({
      sourceCell: { sheet: 'Model', ref: 'A2' },
      originalFormula: 'A1*3',
      normalizedFormula: 'A1*3',
    }));
    expect(preview.proposedModel?.graph.edges).toEqual(model.graph.edges);
    expect(preview.proposedModel?.semver).toBe('1.1.0');
    expect(preview.affectedComponents).toEqual(['Model!A2']);
    expect(preview.affectedOutputs).toEqual(['double-revenue']);
    expect(preview.diff?.entries).toEqual([
      expect.objectContaining({ path: 'outputs.Double Revenue.value', before: 20, after: 30 }),
      expect.objectContaining({ path: 'calculations.Model!A2.formula', semantics: 'semantic', before: 'A1*2', after: 'A1*3' }),
    ]);
    expect(preview.proposedWorkbook?.sheets[0].cells.find((cell) => cell.address.ref === 'A2')?.formula).toBe('A1*3');
    expect(model.outputs[0].value).toBe(20);
    expect(workbook.sheets[0].cells.find((cell) => cell.address.ref === 'A2')?.formula).toBe('A1*2');
  });

  it('rewires a dependency edge and previews the changed downstream impact', () => {
    const source = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(source, XLSX.utils.aoa_to_sheet([[10], [4], [{ t: 'n', f: 'A1*2' }]]), 'Model');
    const workbook = parseWorkbook(Buffer.from(XLSX.write(source, { type: 'buffer', bookType: 'xlsx' })), 'rewire.xlsx');
    const { model } = buildFixture();
    model.graph = buildGraph(workbook);
    model.calculations = [];
    model.parameters.push({ ...model.parameters[0], id: 'volume', name: 'Volume', sourceCell: { sheet: 'Model', ref: 'A2' }, currentValue: 4, originalValue: 4 });
    model.outputs[0] = { ...model.outputs[0], sourceCell: { sheet: 'Model', ref: 'A3' }, value: 20 };

    const preview = previewMutation(model, workbook, {
      actor: { id: 'user-1', type: 'human' },
      rationale: 'Rewire the driver from revenue to volume',
      operations: [{ type: 'setCellFormula', sourceCell: { sheet: 'Model', ref: 'A3' }, formula: 'A2*2' }],
    });

    expect(preview.valid).toBe(true);
    expect(preview.proposedModel?.outputs[0].value).toBe(8);
    expect(preview.proposedModel?.graph.edges).toEqual([{ from: 'Model!A2', to: 'Model!A3' }]);
    expect(preview.proposedModel?.calculations).toEqual([expect.objectContaining({
      sourceCell: { sheet: 'Model', ref: 'A3' },
      originalFormula: 'A2*2',
      dependencies: ['Model!A2'],
    })]);
    expect(preview.diff?.entries).toEqual([
      expect.objectContaining({ path: 'outputs.Double Revenue.value', before: 20, after: 8 }),
      expect.objectContaining({ path: 'calculations.Model!A3.formula', semantics: 'semantic' }),
    ]);
  });

  it('rejects invalid, unsupported, constant-target, and cyclic formula edits', () => {
    const source = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(source, XLSX.utils.aoa_to_sheet([[10], [{ t: 'n', f: 'A1*2' }], [{ t: 'n', f: 'A2+1' }]]), 'Model');
    const workbook = parseWorkbook(Buffer.from(XLSX.write(source, { type: 'buffer', bookType: 'xlsx' })), 'formula-gates.xlsx');
    const { model } = buildFixture();
    model.graph = buildGraph(workbook);

    const invalid = previewMutation(model, workbook, {
      actor: { id: 'user-1', type: 'human' },
      rationale: 'Attempt an unparseable formula',
      operations: [{ type: 'setCellFormula', sourceCell: { sheet: 'Model', ref: 'A2' }, formula: '=SUM(' }],
    });
    expect(invalid.valid).toBe(false);
    expect(invalid.validationIssues).toEqual([expect.objectContaining({ code: 'invalid_formula' })]);

    const unsupported = previewMutation(model, workbook, {
      actor: { id: 'user-1', type: 'human' },
      rationale: 'Attempt an unsupported function',
      operations: [{ type: 'setCellFormula', sourceCell: { sheet: 'Model', ref: 'A2' }, formula: '=WEBSERVICE("https://example.com")' }],
    });
    expect(unsupported.valid).toBe(false);
    expect(unsupported.validationIssues).toEqual([expect.objectContaining({ code: 'unsupported_function' })]);

    const constant = previewMutation(model, workbook, {
      actor: { id: 'user-1', type: 'human' },
      rationale: 'Attempt to convert a constant input',
      operations: [{ type: 'setCellFormula', sourceCell: { sheet: 'Model', ref: 'A1' }, formula: '=A2*2' }],
    });
    expect(constant.valid).toBe(false);
    expect(constant.validationIssues).toEqual([expect.objectContaining({ code: 'formula_cell_not_formula' })]);

    const cycle = previewMutation(model, workbook, {
      actor: { id: 'user-1', type: 'human' },
      rationale: 'Attempt to introduce a cycle',
      operations: [{ type: 'setCellFormula', sourceCell: { sheet: 'Model', ref: 'A2' }, formula: '=A3*2' }],
    });
    expect(cycle.valid).toBe(false);
    expect(cycle.validationIssues).toEqual([expect.objectContaining({ code: 'formula_introduces_cycle' })]);
    expect(cycle.proposedModel).toBeUndefined();
  });

  it('converts a hardcoded input to a formula-driven source and recomputes dependents', () => {
    const source = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(source, XLSX.utils.aoa_to_sheet([[10], [4], [{ t: 'n', f: 'A1*A2' }]]), 'Model');
    const workbook = parseWorkbook(Buffer.from(XLSX.write(source, { type: 'buffer', bookType: 'xlsx' })), 'source-replace.xlsx');
    const { model } = buildFixture();
    model.graph = buildGraph(workbook);
    model.calculations = [];
    model.parameters.push({ ...model.parameters[0], id: 'growth', name: 'Growth', sourceCell: { sheet: 'Model', ref: 'A2' }, currentValue: 4, originalValue: 4 });
    model.outputs[0] = { ...model.outputs[0], sourceCell: { sheet: 'Model', ref: 'A3' }, value: 40 };

    const preview = previewMutation(model, workbook, {
      actor: { id: 'user-1', type: 'human' },
      rationale: 'Replace the hardcoded growth assumption with a formula source',
      operations: [{ type: 'setParameterSource', parameterId: 'growth', formula: '=A1/5' }],
    });

    expect(preview.valid).toBe(true);
    const proposedGrowth = preview.proposedModel?.parameters.find((parameter) => parameter.id === 'growth');
    expect(proposedGrowth).toEqual(expect.objectContaining({
      currentValue: 2,
      source: 'EXTERNAL_DATA',
    }));
    expect(preview.proposedModel?.outputs[0].value).toBe(20);
    expect(preview.proposedModel?.graph.edges).toEqual(expect.arrayContaining([
      { from: 'Model!A1', to: 'Model!A2' },
      { from: 'Model!A2', to: 'Model!A3' },
    ]));
    expect(preview.proposedModel?.graph.edges.filter((edge) => edge.from === 'Model!A2')).toEqual([{ from: 'Model!A2', to: 'Model!A3' }]);
    expect(preview.proposedModel?.calculations).toEqual(expect.arrayContaining([
      expect.objectContaining({ sourceCell: { sheet: 'Model', ref: 'A2' }, originalFormula: 'A1/5' }),
    ]));
    expect(preview.proposedModel?.semver).toBe('1.1.0');
    expect(preview.affectedComponents).toEqual(expect.arrayContaining(['Model!A2', 'Model!A3']));
    expect(preview.diff?.entries).toEqual(expect.arrayContaining([
      expect.objectContaining({ path: 'parameters.Growth.value', before: 4, after: 2 }),
      expect.objectContaining({ path: 'outputs.Double Revenue.value', before: 40, after: 20 }),
    ]));
    expect(model.parameters.find((parameter) => parameter.id === 'growth')?.currentValue).toBe(4);
  });

  it('rejects source replacement on an already formula-driven parameter', () => {
    const { model, workbook } = buildFixture();
    workbook.sheets[0].cells.find((cell) => cell.address.ref === 'A1')!.formula = '1+1';
    const preview = previewMutation(model, workbook, {
      actor: { id: 'user-1', type: 'human' },
      rationale: 'Attempt to replace an already formula-driven input',
      operations: [{ type: 'setParameterSource', parameterId: 'revenue', formula: '=A2*2' }],
    });
    expect(preview.valid).toBe(false);
    expect(preview.validationIssues).toEqual([expect.objectContaining({ code: 'parameter_source_already_formula' })]);
  });

  it('extracts a repeated computation into a virtual component and retargets the consuming formula', () => {
    const source = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(source, XLSX.utils.aoa_to_sheet([[10], [4], [{ t: 'n', f: 'A1*A2' }], [{ t: 'n', f: 'A1*A2+1' }]]), 'Model');
    const workbook = parseWorkbook(Buffer.from(XLSX.write(source, { type: 'buffer', bookType: 'xlsx' })), 'extract.xlsx');
    const { model } = buildFixture();
    model.graph = buildGraph(workbook);
    model.calculations = [];
    model.outputs[0] = { ...model.outputs[0], sourceCell: { sheet: 'Model', ref: 'A3' }, value: 40 };
    model.outputs.push({ ...model.outputs[0], id: 'adjusted-total', name: 'Adjusted Total', sourceCell: { sheet: 'Model', ref: 'A4' }, value: 41 });

    const preview = previewMutation(model, workbook, {
      actor: { id: 'user-1', type: 'human' },
      rationale: 'Extract the shared product into a reusable component',
      operations: [{
        type: 'extractFormula',
        componentId: 'shared-product',
        componentName: 'Shared Product',
        formula: '=A1*A2',
        retargetCell: { sheet: 'Model', ref: 'A3' },
      }],
    });

    expect(preview.valid).toBe(true);
    const proposedSheet = preview.proposedWorkbook?.sheets.find((sheet) => sheet.name === 'XLent Components');
    expect(proposedSheet?.cells[0]).toEqual(expect.objectContaining({
      address: { sheet: 'XLent Components', ref: 'A1' },
      formula: "'Model'!A1*'Model'!A2",
    }));
    const retargeted = preview.proposedWorkbook?.sheets.find((sheet) => sheet.name === 'Model')?.cells.find((cell) => cell.address.ref === 'A3');
    expect(retargeted?.formula).toBe("'XLent Components'!A1");
    expect(preview.proposedModel?.outputs.map((output) => output.value)).toEqual([40, 41]);
    expect(preview.proposedModel?.graph.edges).toEqual(expect.arrayContaining([
      { from: 'Model!A1', to: 'XLent Components!A1' },
      { from: 'Model!A2', to: 'XLent Components!A1' },
      { from: 'XLent Components!A1', to: 'Model!A3' },
    ]));
    expect(preview.proposedModel?.semver).toBe('1.1.0');
    expect(preview.affectedComponents).toEqual(expect.arrayContaining(['XLent Components!A1', 'Model!A3']));
    expect(preview.diff?.entries).toEqual(expect.arrayContaining([
      expect.objectContaining({ path: 'calculations.XLent Components!A1', changeType: 'added' }),
      expect.objectContaining({ path: 'calculations.Model!A3.formula', semantics: 'semantic' }),
    ]));
    expect(model.outputs.map((output) => output.value)).toEqual([40, 41]);
  });

  it('rejects extract when the retarget cell is not a formula or the name collides', () => {
    const { model, workbook } = buildFixture();

    const badTarget = previewMutation(model, workbook, {
      actor: { id: 'user-1', type: 'human' },
      rationale: 'Attempt to retarget a constant',
      operations: [{
        type: 'extractFormula',
        componentId: 'shared-product',
        componentName: 'Shared Product',
        formula: '=A1*2',
        retargetCell: { sheet: 'Model', ref: 'A1' },
      }],
    });
    expect(badTarget.valid).toBe(false);
    expect(badTarget.validationIssues).toEqual([expect.objectContaining({ code: 'retarget_cell_not_formula' })]);

    const nameCollision = previewMutation(model, workbook, {
      actor: { id: 'user-1', type: 'human' },
      rationale: 'Attempt to collide with an input name',
      operations: [{
        type: 'extractFormula',
        componentId: 'shared-product',
        componentName: 'Revenue',
        formula: '=A1*2',
        retargetCell: { sheet: 'Model', ref: 'A2' },
      }],
    });
    expect(nameCollision.valid).toBe(false);
    expect(nameCollision.validationIssues).toEqual([expect.objectContaining({ code: 'duplicate_name' })]);
  });
});