import { Hono } from 'hono';
import { z } from 'zod';
import {
  analyzeFindings, checkAssuranceGate, nextLevel, ASSURANCE_ORDER, runModelTests,
} from '@xlent/core';
import type { AssuranceLevel, AssuranceContext } from '@xlent/core';
import { store, testStore, evidenceStore } from '../store.js';

export const assuranceRouter = new Hono();

const advanceSchema = z.object({
  stewardApproved: z.boolean().optional(),
});

function buildContext(modelId: string): { model: any; ctx: AssuranceContext } | { error: string; status: number } {
  const model = store.getModel(modelId);
  if (!model) return { error: 'Model not found', status: 404 };
  const workbook = store.getWorkbook(modelId);
  const findings = analyzeFindings(model, workbook);
  return {
    model,
    ctx: {
      model,
      tests: testStore.listTests(modelId),
      testResults: null,
      findings,
      evidence: evidenceStore.list(modelId),
      stewardApproved: false,
    },
  };
}

/** GET /assurance/:modelId — current level + gate result for the next level */
assuranceRouter.get('/:modelId', (c) => {
  const built = buildContext(c.req.param('modelId'));
  if ('error' in built) return c.json({ error: built.error }, built.status as any);

  const current: AssuranceLevel = built.model.assuranceLevel ?? 'UNASSESSED';
  const next = nextLevel(current);

  // Run tests to populate the gate's test view
  const tests = testStore.listTests(built.model.id);
  let testResults = null;
  if (workbookAvailable(built.model.id) && tests.length > 0) {
    const workbook = store.getWorkbook(built.model.id)!;
    testResults = runModelTests(built.model, workbook, tests.map(toDef), undefined);
  }

  const ctx: AssuranceContext = { ...built.ctx, testResults };
  const gate = next ? checkAssuranceGate(ctx, next) : null;

  return c.json({
    modelId: built.model.id,
    current,
    next,
    ladder: ASSURANCE_ORDER,
    gate,
    vv: vvBreakdown(tests, built.ctx.findings),
    counts: {
      tests: tests.length,
      autoTests: tests.filter((t) => t.autoGenerated).length,
      userTests: tests.filter((t) => !t.autoGenerated).length,
      criticalFindings: built.ctx.findings.filter((f) => f.severity === 'critical').length,
      evidence: built.ctx.evidence.length,
      hasContract: !!built.model.contract,
    },
  });
});

/** POST /assurance/:modelId/advance — advance to the next level if gates pass */
assuranceRouter.post('/:modelId/advance', async (c) => {
  const built = buildContext(c.req.param('modelId'));
  if ('error' in built) return c.json({ error: built.error }, built.status as any);

  const current: AssuranceLevel = built.model.assuranceLevel ?? 'UNASSESSED';
  const next = nextLevel(current);
  if (!next) return c.json({ error: `Model is already at the highest level (${current})` }, 409);

  const body = await c.req.json().catch(() => ({}));
  const parsed = advanceSchema.safeParse(body);
  if (!parsed.success) return c.json({ error: 'Invalid request', details: parsed.error.flatten() }, 400);

  // Run tests fresh for the gate
  const tests = testStore.listTests(built.model.id);
  let testResults = null;
  if (workbookAvailable(built.model.id) && tests.length > 0) {
    const workbook = store.getWorkbook(built.model.id)!;
    testResults = runModelTests(built.model, workbook, tests.map(toDef), undefined);
  }

  const ctx: AssuranceContext = {
    ...built.ctx,
    testResults,
    stewardApproved: parsed.data.stewardApproved ?? false,
  };
  const gate = checkAssuranceGate(ctx, next);
  if (!gate.canAdvance) {
    return c.json({ error: `Cannot advance to ${next}`, blockers: gate.blockers, current }, 409);
  }

  built.model.assuranceLevel = next;
  store.setModel(built.model);
  return c.json({ modelId: built.model.id, previous: current, current: next });
});

function workbookAvailable(modelId: string): boolean {
  return !!store.getWorkbook(modelId);
}

/** E9.3: derive verification vs validation. structural/mathematical/auto → verification; business/intent → validation. */
function vvBreakdown(tests: any[], findings: any[]) {
  const isValidation = (t: any) => t.category === 'business';
  const verificationTests = tests.filter((t) => !isValidation(t)).length;
  const validationTests = tests.filter(isValidation).length;
  const verificationFindings = findings.filter((f) => f.category !== 'intent').length;
  const validationFindings = findings.filter((f) => f.category === 'intent').length;
  return {
    tests: { verification: verificationTests, validation: validationTests },
    findings: { verification: verificationFindings, validation: validationFindings },
  };
}

function toDef(t: any) {
  return { id: t.id, modelId: t.modelId, name: t.name, category: t.category, assertion: t.assertion, description: t.description, autoGenerated: t.autoGenerated };
}
