import { Hono } from 'hono';
import crypto from 'crypto';
import { analyzeFindings, reconcileContract } from '@xlent/core';
import type { DebugFinding } from '@xlent/core';
import { store, testStore } from '../store.js';

export const findingsRouter = new Hono();

/** GET /findings/:modelId — Classified findings with coverage + impact context */
findingsRouter.get('/:modelId', (c) => {
  const modelId = c.req.param('modelId');
  const model = store.getModel(modelId);
  if (!model) return c.json({ error: 'Model not found' }, 404);
  const workbook = store.getWorkbook(modelId);

  const findings: DebugFinding[] = analyzeFindings(model, workbook);

  // intent: contract vs discovered structure (E8.2)
  if (model.contract) {
    findings.push(...reconcileContract(model, model.contract as any));
  }

  // coverage: outputs lacking any test
  const tests = testStore.listTests(modelId);
  const testedIds = new Set<string>();
  for (const t of tests) {
    const left = t.assertion?.left;
    if (typeof left === 'string' && model.outputs.some((o: any) => o.id === left)) testedIds.add(left);
  }
  if (tests.length > 0) {
    for (const o of model.outputs) {
      if (!testedIds.has(o.id)) {
        findings.push({
          id: crypto.createHash('sha1').update(`coverage|${o.id}`).digest('hex').slice(0, 12),
          severity: 'info',
          category: 'coverage',
          sourceRef: `${o.sourceCell.sheet}!${o.sourceCell.ref}`,
          explanation: `Output "${o.name}" has no test coverage`,
          autoGenerated: true,
        });
      }
    }
  } else {
    findings.push({
      id: 'no-tests',
      severity: 'warning',
      category: 'coverage',
      explanation: 'No tests defined for this model — generate structural tests to begin assurance',
      autoGenerated: true,
    });
  }

  // impact annotation: "affects N outputs" for findings that reference a cell
  const terminalSet = new Set(model.graph.nodes.filter((n) => !model.graph.edges.some((e) => e.from === n)));
  const outEdges = new Map<string, string[]>();
  for (const e of model.graph.edges) {
    if (!outEdges.has(e.from)) outEdges.set(e.from, []);
    outEdges.get(e.from)!.push(e.to);
  }
  const reach = (start: string): number => {
    const seen = new Set<string>();
    const q = [start];
    while (q.length) {
      const cur = q.shift()!;
      for (const n of outEdges.get(cur) ?? []) {
        if (!seen.has(n)) { seen.add(n); q.push(n); }
      }
    }
    return [...seen].filter((n) => terminalSet.has(n)).length;
  };
  for (const f of findings) {
    if (f.sourceRef) {
      const n = reach(f.sourceRef);
      f.reachCount = n;
      if (n > 0) f.impact = `affects ${n} output${n === 1 ? '' : 's'}`;
    }
  }

  const order = { critical: 0, warning: 1, info: 2 } as const;
  findings.sort((a, b) => order[a.severity] - order[b.severity]);

  return c.json({ modelId, findings, count: findings.length, workbookAvailable: !!workbook });
});
