import { Hono } from 'hono';
import crypto from 'crypto';
import { runModelTests, generateStructuralTests } from '@xlent/core';
import type { ModelTestDefinition, EvidenceRecord } from '@xlent/core';
import { store, testStore, evidenceStore } from '../store.js';
import { createTestSchema, createTestsSchema, runTestsSchema } from '../schemas.js';

export const testsRouter = new Hono();

/** GET /tests/:modelId — List tests for a model */
testsRouter.get('/:modelId', (c) => {
  const modelId = c.req.param('modelId');
  const model = store.getModel(modelId);
  if (!model) return c.json({ error: 'Model not found' }, 404);

  const tests = testStore.listTests(modelId);
  return c.json({ modelId, tests, count: tests.length });
});

/** POST /tests/:modelId — Create test(s) for a model */
testsRouter.post('/:modelId', async (c) => {
  const modelId = c.req.param('modelId');
  const model = store.getModel(modelId);
  if (!model) return c.json({ error: 'Model not found' }, 404);

  const body = await c.req.json();

  // Accept single test or batch
  const isBatch = 'tests' in body;
  if (isBatch) {
    const parsed = createTestsSchema.safeParse(body);
    if (!parsed.success) return c.json({ error: parsed.error.flatten() }, 400);

    const created: string[] = [];
    for (const t of parsed.data.tests) {
      const id = crypto.randomUUID();
      testStore.addTest(modelId, { id, name: t.name, category: t.category, assertion: t.assertion, description: t.description, autoGenerated: false });
      created.push(id);
    }
    return c.json({ modelId, created, count: created.length }, 201);
  } else {
    const parsed = createTestSchema.safeParse(body);
    if (!parsed.success) return c.json({ error: parsed.error.flatten() }, 400);

    const id = crypto.randomUUID();
    testStore.addTest(modelId, { id, name: parsed.data.name, category: parsed.data.category, assertion: parsed.data.assertion, description: parsed.data.description, autoGenerated: false });
    return c.json({ modelId, testId: id }, 201);
  }
});

/** DELETE /tests/:modelId/:testId — Delete a single test */
testsRouter.delete('/:modelId/:testId', (c) => {
  const { modelId, testId } = c.req.param();
  const model = store.getModel(modelId);
  if (!model) return c.json({ error: 'Model not found' }, 404);

  const deleted = testStore.deleteTest(testId);
  if (!deleted) return c.json({ error: 'Test not found' }, 404);
  return c.json({ deleted: true });
});

/** POST /tests/:modelId/generate — Generate structural tests */
testsRouter.post('/:modelId/generate', (c) => {
  const modelId = c.req.param('modelId');
  const model = store.getModel(modelId);
  if (!model) return c.json({ error: 'Model not found' }, 404);

  const structural = generateStructuralTests(model);

  for (const test of structural) {
    testStore.addTest(modelId, { id: test.id, name: test.name, category: test.category, assertion: test.assertion, description: test.description, autoGenerated: true });
  }

  return c.json({ modelId, generated: structural.length, tests: structural.map(t => t.id) }, 201);
});

/** POST /tests/:modelId/run — Execute all tests for a model */
testsRouter.post('/:modelId/run', async (c) => {
  const modelId = c.req.param('modelId');
  const model = store.getModel(modelId);
  if (!model) return c.json({ error: 'Model not found' }, 404);
  const workbook = store.getWorkbook(modelId);
  if (!workbook) return c.json({ error: 'Workbook not found' }, 404);

  const body = await c.req.json().catch(() => ({}));
  const parsed = runTestsSchema.safeParse(body);
  const overrides = parsed.success ? parsed.data.overrides : undefined;

  const testDefs = testStore.listTests(modelId);
  if (testDefs.length === 0) return c.json({ modelId, results: [], allPass: true, count: 0 });

  const definitions: ModelTestDefinition[] = testDefs.map((t: any) => ({
    id: t.id,
    modelId: t.modelId,
    name: t.name,
    category: t.category,
    assertion: t.assertion,
    description: t.description,
    autoGenerated: t.autoGenerated,
  }));

  const results = runModelTests(model, workbook, definitions, overrides as any);
  const allPass = results.every((r) => r.status === 'pass' || r.status === 'skip');

  // Store evidence if requested
  const evidence = c.req.query('evidence') === 'true';
  let evidenceId: string | undefined;
  if (evidence) {
    const dataHash = crypto.createHash('sha256').update(JSON.stringify(results)).digest('hex');
    const evidenceRecord: EvidenceRecord = {
      id: crypto.randomUUID(),
      modelId,
      modelVersion: model.version ?? 1,
      executedAt: new Date().toISOString(),
      inputs: {},
      overrides: (overrides as any) ?? [],
      outputs: {},
      tests: results,
      allTestsPass: allPass,
      checksum: dataHash,
      reproducible: true,
      purpose: 'manual',
    };
    evidenceStore.store(evidenceRecord);
    evidenceId = evidenceRecord.id;
  }

  return c.json({ modelId, results, allPass, count: results.length, evidenceId });
});

/** GET /tests/:modelId/evidence — List evidence records */
testsRouter.get('/:modelId/evidence', (c) => {
  const modelId = c.req.param('modelId');
  const model = store.getModel(modelId);
  if (!model) return c.json({ error: 'Model not found' }, 404);

  const limit = Math.min(parseInt(c.req.query('limit') ?? '20', 10), 100);
  const records = evidenceStore.list(modelId, limit);
  return c.json({ modelId, evidence: records, count: records.length });
});

/** GET /tests/:modelId/evidence/:evidenceId — Get single evidence record */
testsRouter.get('/:modelId/evidence/:evidenceId', (c) => {
  const { modelId, evidenceId } = c.req.param();
  const model = store.getModel(modelId);
  if (!model) return c.json({ error: 'Model not found' }, 404);

  const record = evidenceStore.get(evidenceId);
  if (!record || record.modelId !== modelId) return c.json({ error: 'Evidence not found' }, 404);
  return c.json(record);
});
